### ISSUE TITLE
Support include search paths

### ISSUE THREAD

**Issue by RPGHacker** [RPGHacker/asar#10]
Add support for include search paths like in C compilers etc. Should work with any and all Asar commands (and functions etc.) that reference other files (incsrc, incbin, table, readfile1() etc.).

Include search paths should be configurable via command line parameters and via a TXT file next to Asar which is automatically checked and read if it exists.

Includes should be resolved with the following priority (from highest to lowest, only applies to relative paths):

1. Check if the file exists in a path relative to the file currently being assembled.
2. Check if the file exists in any search path passed in via the command line.
3. Check if the file exists in any search path passed in via a TXT file.
4. (Maybe) check if the file exists within one (or multiple) search path(s) relative to the current Asar executable (not sure if this is a good idea or if it's better to leave that up to the TXT file)

Also make sure to support this functionality in the DLL interface (via a new function or whatever).

**Comment by RPGHacker** [comment]
The functionality itself is there (although Ladida still mentioned having some problems with includes in the Asar thread that I'd like taking a look at if I had some code that reproduced the problem).

The part that is still missing is the "read include paths from a TXT file" part, which I consider quite important because it makes it easy to distribute "drag & drop" libraries on SMW Central (or whereever). Basically, it would allow you to just unzip the contents of a ZIP file into the Asar directory and have Asar automatically add it as an include path when running, based on the contents of a TXT file distributed in the ZIP file. This would allow the use of include paths without using Asar from the command line, which would probably help inexperienced users who use Asar by double-clicking on it.

We would also need an equivalent to that for the Asar DLL so that tools could do the same. I don't know if we should just make it look for a TXT file next to the DLL, because that seems kinda finicky for a number of reasons. Something that could work here, though, would be to add a function to the API, something like "asar_parse_include_paths_from_txt()" (or whatever). This function, when passed the path to a TXT file, would open it, parse it, and then return include paths in a format that could be easily passed to asar_patch_ex() as include paths. However, one problem of this approach would be that order of include paths wouldn't be enforced. Maybe a better alternative would be to extend the asar_patch_ex() parameter so that we could pass it the path to a TXT file to use for this.

But yeah, that's basically the gist of it.

**Comment by randomdude999** [comment]
You implemented the txt file search paths too, can this be closed now?

**Comment by RPGHacker** [comment]
Yup, I think so. Forgot to close it.
