### ISSUE TITLE
Tests for DLL functions

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#105]
We should have some tests that, instead of testing the functionality of Asar, test the functionality of the functions in the DLL.
For the C/C++ binding, this could be achieved by adding some code to the end of test.cpp that only runs when testing the DLL.
For the Python and C# bindings we could have a small separate program written the respective language.
The Python and C/C++ binding tests should run on both Linux and Windows, but the C# binding test should only run on Windows (it's possible to compile C# programs using Mono on Linux, but to run them you'd need Wine since Mono can't use the non-C# asar.dll).

* [ ] C/C++ binding tests
* [ ] Python binding tests
* [ ] C# binding tests

**Comment by randomdude999** [comment]
Just tested and apparently Mono assemblies can load libasar.so just fine, so I guess if we get Mono set up on Travis then we could also test the C# binding on Linux.

**Comment by randomdude999** [comment]
At this point I have a "framework" for testing the DLL functions in every language on every platform. Now all that remains is to actually write the tests.

**Comment by trillllian** [comment]
better 5.5 years late than never i guess

currently tests cover every API function to what i would call a reasonable degree, so considering this done
