### ISSUE TITLE
Bad error messages about missing files on Linux

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#106]
(I'm not sure if this affects Windows too. It might.)
On linux, if I try to `incsrc` a non-existent file, then the reported error is `error: (E5015): Failed to open file ''.`, which is missing the filename.
Also, the location of the faulty `incsrc` is not reported either.
Note that with `incbin`, the filename is shown correctly (the error is also number 5016 instead of 5015).

**Comment by RPGHacker** [comment]
If I remember correctly, the error printing functions only do an snprintf(), so if the file name doesn't show up, maybe the parameter was not passed to the calling function as vararg? Or who knows, maybe the varargs in that function don't work correctly on Linux in th efirst place. But yeah, the first thing I'd do here would be to search the solution for all occurences of that error's enum value. If a parameter is missing in some place, it should be fairly easy to spot.

**Comment by RPGHacker** [comment]
Just fixed a few bugs in path normalization. Do any of those fixes happen to fix this problem as well? I did just run into this problem myself on Windows, though it was as a result of a previous fix introducing a new bug, so not sure if related to this.

**Comment by RPGHacker** [comment]
Also just commited another fix. Was probably a bad idea in the first place to use absolutepath to print the error message. It's the normalized path and, if something goes wrong, can also end up empty.

**Comment by randomdude999** [comment]
Now it shows the filename, but it still uses error E5015 instead of E5016, and doesn't show the location of the incsrc.

**Comment by RPGHacker** [comment]
6d9232dfe4bd0f1511ec9df88372077ebd9eac09 should finally make this give proper error messages.

**Comment by randomdude999** [comment]
Fixed in 80519b6f9c5d9b85be5445079b5b7640173bfc6a.
