### ISSUE TITLE
Allow to set defines via command line

### ISSUE THREAD

**Issue by RPGHacker** [RPGHacker/asar#11]
Add support to set defines via command line, like in C compilers etc. Maybe also add support to set defines via a TXT file Asar automatically searches for and includes if it exists.

**Comment by randomdude999** [comment]
IMO it would also be useful to be able to set defines to be used with the DLL's asar_patch function. Right now I'm having to use something like this at the start of my generated ASM file:

    !variable = %VARIABLE%

and then replace %VARIABLE% with the actual value.

**Comment by RPGHacker** [comment]
Good thing you mention it, I forgot to add that here. I want to have this feature for both the stand-alone application, as well as the DLL interface. Probably via a new funcion or something like that.

**Comment by randomdude999** [comment]
One slight problem with this though: adding this would mean choosing some command line argument parsing framework/library/whatever. `getopt` is Linux only, but I found what looks like a decent cross-platform replacement [here](https://gist.github.com/superwills/5815344). I don't think it's worth messing with `getopt_long`.

**Comment by RPGHacker** [comment]
I don't think command lines need to be parsed for the DLL interface, that seems like an overcomplication of the problem. I think the better solution is to just add a new function to the DLL API for that.

Something like this

```
void asar_add_define(const char* identifier, const char* value);
```

Which you would call like this

```
// This would do the equivalent of
// !debug_mode = 1
asar_add_define("debug_mode", "1");
asar_patch(...);
```

**Comment by randomdude999** [comment]
I actually meant the CLI interface. Also, you would need a new asar_patch function that doesn't clear defines (by calling asar_reset).

**Comment by Horrowind** [comment]
Instead of a text file with includes maybe just allow multiple files to be specified on the command line, which will be assembled in order:
```./asar includes.asm main.asm```
where `includes.asm` contains
```
!define1 = value1
!define2 = value2
...
```

Command line parsing seems to be easy, so I would avoid a dependency on some library for this. It might be tricky if someone wants to have wide characters on windows though. But we should only have this problem for file names, since asars assembly language is ascii only, I suppose?!

**Comment by RPGHacker** [comment]
Is this a Linux thing? I'm not too familiar with Linux, but on Windows, the calling application is responsible for wrapping command line arguments correctly, and I assumed it would be the same for Linux. If we do this on Windows

 ```
asar.exe -dmy_define="lda #$00 : stat $00"
 ```

our application receives

 ```
-dmy_define=lda #$00 : stat $00
 ```
as a single command line argument. Similarly, if we do

 ```
asar.exe --define my_define="lda #$00 : stat $00"
 ```

our application receives the command line arguments

 ```
--define
my_define="lda #$00 : stat $00"
 ```

Both of these cases are reasonably simple to parse. I don't think we need a lib for this, unless everything is vastly different on Linux.

**Comment by RPGHacker** [comment]
> Instead of a text file with defines maybe just allow multiple files to be specified on the command line, which will be assembled in orde

Well, the purpose of the text file is really so that SMW Central can distrubte an SMW standard lib at some point which you just have to drag & drop into the Asar directory for it to be found. That's why I want to avoid having it as another command line argument. Of course we could have both if the benefits are huge enough.

> But we should only have this problem for file names, since asars assembly language is ascii only, I suppose?!

Yeah, it is. I'm not sure about file names (as used in incsrc etc.), but the language itself (including custom identifiers) are all-ASCII.

**Comment by Horrowind** [comment]
It should be the same on linux, as far as I remember. We might also want to parse
```
--define my_define= "lda #$00 : sta $00"
--define my_define ="lda #$00 : sta $00"
--define my_define = "lda #$00 : sta $00"
```
which is slightly more difficult to parse since you get up to four tokens, but still simple.

**Comment by RPGHacker** [comment]
We could do that, but I think it's also reasonable enough to enforce a certain usage of the command line arguments and only allow the one without spaces. I think pretty much all well-known compilers (MSVC, Clang etc.) would fail in any of those three listed cases, and it's technically the user's responsibility to make sure they're following the protocol, I'd prefer keeping the code simple here over giving the user a minor bit of extra convenience.

**Comment by RPGHacker** [comment]
Forgot to respond to this:

> Also, you would need a new asar_patch function that doesn't clear defines (by calling asar_reset).

I was actually planning to add one, anyways. Probably an asar_patch_ex() function, taking a asar_patch_params_ex struct or something like that. The struct would contain a size variable as its first member, specifying the size of the struct. This would allow us to add new params in the future without changing the function signature and without breaking backwards-compatibility. This struct could then contain stuff like "initial defines", "include paths" etc.

**Comment by randomdude999** [comment]
I was thinking more like a separate function (maybe still named patch_ex) with the same signature as asar_patch that simply didn't reset stuff, and then we could have functions like setdefine and addincludepath or something. IMO that would be even better for backwards compatibility.

**Comment by RPGHacker** [comment]
Well, we can always just put a "disable_reset" variable into the struct. I'm not a fan of the "set by function" approach, though, because it means adding even more global state to Asar - and Asar already has loads of global state as is. Global state is why functions like asar_reset() are needed in the first place. Adding defines and stuff per functions ultimately just means there's more stuff we have to think about cleaning up somewhere. For this reason, I want to avoid adding more functions that set a global state or require a global state.

**Comment by Horrowind** [comment]
> I was actually planning to add one, anyways. Probably an asar_patch_ex() function, taking a asar_patch_params_ex struct or something like that. The struct would contain a size variable as its first member, specifying the size of the struct. This would allow us to add new params in the future without changing the function signature and without breaking backwards-compatibility. This struct could then contain stuff like "initial defines", "include paths" etc.

While I agree that Asar has to much global state, and we should definitely look into removing global state, I am not so sure if backwards compatibility is a real concern here. As far as I see, there will be issues if I try to run a program expecting a newer version of the DLL with an old version of the DLL, the size field does not help here. It only helps if we have an old tool with a newer version of the DLL. But that should be easily fixed by just recompiling the tool with the new header file.

Am I missing something here?

**Comment by RPGHacker** [comment]
Old tools using newer Asar versions is precisely what I meant. It's true that recompiling the tool is often all that's needed, but that requires someone to actually do it, which for some tools noone does (or they take their time doing so). For that reason, I do think there is something to be gained from supporting this.

That being said, I do have another reason for wanting to do it this way: we can easily add new parameters to asar_patch() in the future without having to add any new functions. If we don't do it this way, we have to either
* Change the asar_patch() function (breaking code compatibility with applications using the DLL)
* Add new setter functions (adding more global state to Asar)
* Or add a new variant of asar_patch() every time we want to add a new parameter
For those reasons, I don think it's the best solution in this case.
