### ISSUE TITLE
SuperFX branches are off by one

### ISSUE THREAD

**Issue by Ersanio** [RPGHacker/asar#110]
Branch parameters in SuperFX are off by one. They'll have to be +1.

### Example of the bug

**Code**
```
	lsr ;r0>>2
	beq .test_branch ;zero result, branch is taken
	nop
	rpix
.test_branch
	color
```

**Debugger**
```
108814 lsr               S:0020 zcnv R0 :0000 
108815 beq   $8819       S:0022 Zcnv R0 :0000 
108819 plot              S:0022 Zcnv R1 :fff0 R2 :0004 
10881a color             S:0022 Zcnv R0 :0000 R1 :fff0 R2 :0004 
```
This isn't a case of a faulty debugger/disassembler, as I did have a bogus `mult r0` in some other code, and it did modify the contents of r0.

### Explanation
In this case, `beq $8819` has to be `beq $881a`. Currently this assembles as `beq $03`, as the following 2 instructions after beq are 3 bytes in size. Because it's off by one, it reads the second half of `rpix` as `plot`. `rpix` is `$3D4C` in hex, while `plot` is `$4C`. Please refer to snes dev manual 2-9-19 for the proper implementation. In this case, the correct implementation is 'beq $04'. Here's the branch parameters for each opcode you want to reach, each byte on a separate line:
```
108815 beq
108816 $03   ; +$00
108817 nop   ; +$01
108818 rpix  ; +$02  ; rpix is two bytes
108819 rpix  ; +$03
10881a color ; +$04
```

Negative branches are also affected by this. In that case, the backward branch goes one byte backwards too many.

I also have the same issue with `bcc`, so I think it's safe to assume that all branches are affected by this bug. Please add +1 to the branch values.

**Comment by RPGHacker** [comment]
Weird. Is this new in Asar 1.60, or was the same bug in earlier versions? It seems like quite a major bug, so if it's the latter, that would be quite surprising.

**Comment by Ersanio** [comment]
Unfortunately, this bug has been present in asar as early as version 1.37. I'd try the versions before that, but my code doesn't assemble in those.

**Comment by RPGHacker** [comment]
Alright, it's something that will have to be fixed then.

Looking at it, tests/arch-superfx.asm doesn't seem like a great test for this to begin with, it doesn't use any labels at all, so there currently isn't even any branch label validation for Super FX at all. We will have to add a few labels in there.

I'm kinda surprised, though, wasn't Super FX support in Asar used much? I thought it would have been used for at least YI hacking.

**Comment by Ersanio** [comment]
I'm also surprised, so I decided to try this in another emulator: [http://fusoya.eludevisibility.org/sfx/index.html](http://fusoya.eludevisibility.org/sfx/index.html)

Maybe it is the case of a faulty debugger after all. In this tracer, I get the following trace:

```
10:8814 03       lsr             Z=1
10:8815 09 03    beq $881a       r15=$881a
10:8819 01       nop            
10:881a 4e       color          
```

108819 should contain the hex value $4C but due to SuperFX's pipeline processing, it executes the NOP there instead, which sounds like it's the correct way of doing things.

Guess in the end, this is a bug in the bsnes-plus debugger...

(makes me wonder what debugger YI hackers use, could give that a try too)

**Comment by RPGHacker** [comment]
Maybe @Raidenthequick (not sure if this tagging thing works out) could say something about this, since he used to hack Yoshi's Island and also did some stuff for the Super FX support in Asar.

**Comment by Raidenthequick** [comment]
Yeah I'm pretty sure most tracers will show the wrong thing because of the pipeline. I came across that during many a debugging & tracing session. As for asar I'm 100% sure it is fine with super fx as I have the entire Yoshi's Island dfisassembly working and assembling 100% clean. Look at these banks for proof:

https://github.com/Raidenthequick/yoshisisland-disassembly/blob/master/disassembly/bank08.asm
https://github.com/Raidenthequick/yoshisisland-disassembly/blob/master/disassembly/bank09.asm
https://github.com/Raidenthequick/yoshisisland-disassembly/blob/master/disassembly/bank0A.asm
https://github.com/Raidenthequick/yoshisisland-disassembly/blob/master/disassembly/bank0B.asm

**Comment by RPGHacker** [comment]
Thanks for the input! Good to know it doesn't seem to actually be an Asar bug, so I'll go ahead and close the issue.
