### ISSUE TITLE
Make freespace more customizable

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#114]
Requested by Ladida on the dsicord
It should be possible to change the banks that `freecode`/`freedata` look in, and also disable using RATS tags.

**Comment by RPGHacker** [comment]
I'm assuming "disable rats" is intended for stuff that is only ever assembled once? (Like assembling a ROM from source for example).

**Comment by randomdude999** [comment]
Yeah, probably.

**Comment by randomdude999** [comment]
woah both of these were implemented yesterday (or well the no rats part has been working for half a year lol)
