### ISSUE TITLE
Hang when inverse of non-existent label is passed to repeatable instruction

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#118]
by repeatable instruction i mean ones like INC, DEC, ASL, etc where an operand specifies amount to repeat the instruction.
```asm
INC #~nonexistent_label
```
hangs. Theory is that a nonexistent label's address is 0 in the earlier passes, and ~0 == 0xFFFFFFFF (or however many bytes an int is). This means the INC tries to repeat for a really long time.

**Comment by RPGHacker** [comment]
Should passing labels to this instruction be supported in the first place? IMO this will likely lead to the same problem as labels in conditionals (different output in different passes).

**Comment by x10A94** [comment]
The only use I can see for this would be e.g. `LSR #data_end-data`, but even then, I can't come up with a use case for it.

**Comment by Horrowind** [comment]
I think I came across these things when I tried to code-golf the smallest input to asar which triggers the moving labels error. If I remember correctly, using labels and repeatable instructions was very effective.

(I am pretty sure this does not count as a legitimate use case...)
