### ISSUE TITLE
Add support for compiling code from a memory buffer rather than a file

### ISSUE THREAD

**Issue by RPGHacker** [RPGHacker/asar#12]
Add support for compiling code from a memory buffer rather than a file to the DLL interface. This let's us avoid having to create files like "tmp.asm" and similar in third-party tools. Might also slightly increase performance.

Functionality also needs to extend to file-based commands/functions etc. Proposal: add some kind of mount point that automatically makes file-based functions read from memory instead of file. For example,
`incsrc "mem:/0x94FA783E"`
could automatically attempt to read memory at location 0x94FA783E rather than opening a file.

**Comment by Horrowind** [comment]
Your proposal will need to be extended to also specify a length. You can assume NULL-terminated strings for `incsrc`, but not for `incbin`.

How I am considering to implement this in my assembler: Create a virtual file system layer, which does not need to be complicated, just a map from filenames to strings.

This could be done with functions like:
`void map_file(virtual_file_system* vfs, char* file_name, void* buffer, unsigned int length);`
`void map_file_from_fs(virtual_file_system* vfs, char* file_name); //just load from fs`

Then I can assemble 'main.asm' which I loaded from the file system, which wants to use `generated_file.asm`, which resides in memory.

**Comment by randomdude999** [comment]
Implemented with the memory files I recently merged.
