### ISSUE TITLE
Negative values are screwed up

### ISSUE THREAD

**Issue by Alcaro** [RPGHacker/asar#121]
[C++17 (n4713), 7.10 Floating-integral conversions](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4713.pdf):
> A prvalue of a floating-point type can be converted to a prvalue of an integer type. The conversion truncates; that is, the fractional part is discarded. The behavior is undefined if the truncated value cannot be represented in the destination type.

(Similar rules exist in C11 6.3.1.4.1, and I believe all older and future versions of C and C++.)

This causes various machine-dependent and optimization-level-dependent behavior upon encountering db -1. (Older versions of Asar screw up on dd $FFFFFFFF instead, but this changed around commit 174f51db8916c8a967344f46a306d2222991014c.)

Lazy solution: Cast to int64_t before casting to (u)int32_t (or synonyms, int / unsigned).  
Proper solution: ...can't think of any. Asar is a huge hackjob anyways, fixing that one seems fairly misprioritized.

**Comment by Alcaro** [comment]
Tested a bit further; 'dd $87654321+0' doesn't work very well either, and some possible fixes to that one would make 'dd (-2)/2' return FF FF FF 7F, or 'dd $FF000000/256' return 00 00 FF FF. Probably better to switch to int64_t all the way, rather than just as an intermediate to enforce truncation.

(Don't worry about 32bit systems, int64_t is emulated in software on those. It may yield a slowdown on large patches, but Asar's three-pass reparse-everything-also-if-then-else-string-comparison-ladders setup probably dominates the math module. Not sure about printf, though.)

On a mostly related note, bit shifts by negative amounts, amounts greater or equal to bit count, and right shifts of negative values, are all undefined or implementation-defined.

For example db 1>>32; randomdude's bot (an ARM Raspberry Pi) returns 0, AlcaRobot (x86) says 1. Fair chance dd (-1)>>16 would also be machine dependent, but it's kinda hard to test with the above bug nearby.

**Comment by RPGHacker** [comment]
Admittedly I only understood a fraction of all of this. If I understood you correctly, a lot of math in Asar is currently undefined/system-dependent because of float -> uint32 conversion, and the examples you listed above break on some systems, mostly because they're using negative numbers which uint32 can't represent, causing the undefined behavior. Is that about right? In that case, yeah, int64 seems like the simple and logical fix. We should probably put all of the examples above into a file for the test suite.

As for the bit shift, I guess it can't hurt to throw, at the very least, compatibility warnings on some unreasonable-looking inputs.

**Comment by randomdude999** [comment]
I believe the best solution to this would be to just manually perform 2s complement negation in getnum (which is responsible for the double->uint32 conversion). Then we could have another function that doesn't perform that conversion and returns a int64.

**Comment by randomdude999** [comment]
Just pushed a few commits on the better-rounding branch (https://github.com/RPGHacker/asar/tree/better-rounding) that should mostly fix this issue. That solution works with all the tests alcaro suggested. I'd like some more people to look over it though.
