### ISSUE TITLE
Document quote escape

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#129]
A quote can be escaped in a double-quoted string by a double quote.
That sounded confusing so here's an example:
```
print "Hello "" world!"
```
prints `Hello " world!`.

**Comment by p4plus2** [comment]
That almost looks more like a bug than a feature....hah.  Is there a reason not to do the more typical backslash?

**Comment by randomdude999** [comment]
@Alcaro mind explaining?
I'm pretty sure it's not a bug: https://github.com/RPGHacker/asar/blob/ec416569952904dd1cbce5438e668ad30b4c9ee4/src/asar/libstr.h#L496-L500

**Comment by Alcaro** [comment]
no explaining available, I've suppressed all memories of how asar works.

Drugs probably.

**Comment by Alcaro** [comment]
actually, how old is the backslash escape feature? I don't think I added that. Double quote to emit single quote is perfectly sane if no other escape mechanism exists.

**Comment by RPGHacker** [comment]
Backslash escaping is fairly new, it was only added with 1.60, I think? Didn't know about double quote escaping, though.

**Comment by p4plus2** [comment]
I wonder what the proper fix should be...

**Comment by RPGHacker** [comment]
Personally, I'd just add it to the documentation since having an escape sequence for this in some form isn't a bad idea, anyways.

**Comment by p4plus2** [comment]
Added to documentation.
