### ISSUE TITLE
Upload build artifacts to FTP server

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#131]
I recently acquired myself a server (well, it's my Raspberry Pi that I've had for a few years, but I recently got a domain name for it). This means I could set up Travis and Appveyor to automatically upload build artifacts there. This would make it easier to package releases, and it would mean we could distribute Linux binaries too (since there's no way to manually download them from Travis). Also it would make the beta builds have more consistent URLs. (Currently, the beta exe URL is https://ci.appveyor.com/api/projects/RPGHacker/asar/artifacts/build/asar/MinSizeRel/asar-standalone.exe?branch=master&job=Environment%3A%20CMAKE_TARGET%3DVisual%20Studio%2014%202015%2C%20PLATFORM%3DWin32%2C%20CMAKE_PLATFORM_TOOLSET%3D-T%20v140_xp which encodes a bunch of information about the build itself that is prone to change. There is no way to make it shorter without using an external artifact server.)

**Comment by RPGHacker** [comment]
Sounds cool, if you have experience with it and know how to do it. I've personally never worked with build servers and have no idea how to set anything up, but I guess it would be nice to have some nice, human-readable link for Asar builds.

**Comment by randomdude999** [comment]
Late response but I thought I might let you know why I never finished this. Turns out that neither Travis nor Appveyor can connect to IPv6-only servers, and I don't have an IPv4 address. So unless we get a real server (or an FTP account on someone else's server) this won't really happen.

**Comment by RPGHacker** [comment]
Oh well, not really a major problem. I mean, if we're honest, this was always really just a nice-to-have thing and not something we urgently needed. I don't think having automatic public builds of the WIP branch is too important, and whenever we do need them, we do at least still have the Windows builds from AppVeyor. Cases where we need anything else will probably be rare.

**Comment by RPGHacker** [comment]
(Speaking of "WIP" branch: I completely forgot that we wanted to make one at some point so that development changes don't automatically affect the master branch)

**Comment by randomdude999** [comment]
oh right i implemented this at some point
