### ISSUE TITLE
1.70 release planning

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#132]
Should we release 1.70 at C3, like we did with 1.60?

Here's the current changelog, since 1.61:
* Fixed 5 segfaults (#115, #116, #117, #119, #128), of which 1 could be encountered by a normal person applying a normal patch (#119)
* 1.60 introduced a "bug" which caused Asar to be ~2x slower than it needed to be. This has been fixed, causing a ~2x speedup.
* values greater than $80000000 (MAXINT32+1) should be handled better.
* fixed a freespace leak when using prot
* Made it easier to cross-compile the windows version of asar on linux.

Admittedly this is mostly bugfixes, but i'm hoping to finish #120 and #72 (and maybe merge #125) before C3 too.

**Comment by RPGHacker** [comment]
I'm not opposed to a C3 release (there's probably nothing to lose from it), although this time I likely won't be able to help with anything, unfortunately. Some of those features and fixes definitely sound nice enough to warrant a new release, though, so feel free to go ahead and release a version for C3. If you do, make sure to keep changelog and manual up-to-date (it's easy to forget about them whenever checking in stuff).

**Comment by randomdude999** [comment]
i released 1.70 and got nice positive feedback so i'll close this now i guess
