### ISSUE TITLE
sfxrom broken in v1.61 (needs verification)

### ISSUE THREAD

**Issue by RPGHacker** [RPGHacker/asar#134]
Kinda forgot to make an issue for this, but according to [this thread](https://www.smwcentral.net/?p=viewthread&t=95781), `sfxrom` seems to be broken in in the current Asar version. It wouldn't surprise me, as it's not really a feature that I think was tested a whole lot be either of us, seeing how it's relatively rarely used for SMW hacking. I didn't verify this bug yet (and don't even quite know how to, I'm not very familiar with this mapping mode). Might be a good idea to add a test for this at some point to prevent errors with it from slipping through.

**Comment by randomdude999** [comment]
I asked Vitor on discord about this. He only said he knew it was related to freespace support and asked DiscoTheBat for more details. Now i'm just waiting for him to reply.

**Comment by randomdude999** [comment]
Turns out freespace support was broken because there was no code handling sfxrom in pctosnes.
