### ISSUE TITLE
Crash when using C# API and more than 1 warning/error is thrown

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#135]
(well, i'm not sure if it's directly a crash, but it definitely causes invalid pointers in the application using the DLL.)
In 1.60, the warning/error system was reworked and a new field was added to the errordata struct. But that changed the size of the struct, which was a breaking change for applications that did not know about it, since errordatas are passed as a pointer treated as an array. Only the minor API version was bumped though. This means that 1.60, 1.61 and 1.70 are technically incompatible with the 1.50 DLL, despite what their API version says. The C# wrapper hasn't been updated to take it into account either so multiple warnings will crash it even when using the newest release of the C# wrapper.

**Comment by randomdude999** [comment]
I'm still not quite sure what we want to do about this. Someone on discord brought up that keeping compatibility with 1.50 is more important since the developers of applications that use 1.60/1.70 DLLs are more likely to still be active, so they could rebuild their programs against the newest DLL.
This means that geterrors still needs to return a pointer to an array of errordatas with the old size. We'll then need a new function that returns the new errordata with the error IDs. Ideally I'd like it if we could extend the errordata struct without this mess happening again.
We could make the return value of (the new) geterrors an array of pointers, which means we could add as many fields as we wanted, but it might become a bit messy to manage it.
We could also just reserve some amount of space in the errordata struct in the form of `char unused[n]`, but then we'd need to make sure the struct size doesn't change when adding a field that has a different width on different platforms (like a pointer).

**Comment by RPGHacker** [comment]
What exactly did our DLL compatibility policy use to be, anyways? That old applications are supposed to be compatible with new DLLs as long as their API version doesn't change? I don't quite remember.
I suppose it's not sufficient to just change the API version retroactively?
Maybe we should think a bit about what we want our compatibility policy to be going forward and then document it somewhere so that we have something to refer to (since I do keep forgetting what our consensus was). If we do want to keep maintaining some form of DLL compatibility, we should also think of some way to test and ensure this compatibility so that we can prevent incompatibilities like this more easily in the future. I don't really have any ideas for this, though. How does one properly automate something like that?

**Comment by randomdude999** [comment]
Old apps should work with new DLLs, as long as the major API version is the same for both the DLL and the app. While just bumping the API version to 400 would be a solution, it would break backwards compatibility with old apps, which I really don't like.

The compatibility policy should be "try to avoid breaking API changes, but if you must, bump the API major version too" AFAIK. This could be mentioned in the repo's dev readme.

>how does one properly automate that?

my guess would be "keep latest released version on FTP somewhere, then use Travis to test beta DLL against old headers after every commit". Not sure if there's a better way. In any case, this point is related to #105 (which I've been slacking off on for quite a while, lol), and my solution is related to #131 too.

**Comment by RPGHacker** [comment]
That does sound reasonable. Yeah, we should probably mention that in the README.md under a new compatibility section or something like that.

Yeah, that was basically the only idea for a compatibility test I had as well, but it would unfortunately mean yet another thing we would have to make and then maintain. Yikes! 😣
I guess there aren't really any alternatives, though (besides, of course, not having any automated tests).

And don't worry about "slacking off", I mean, I haven't touched Asar in ages myself and it will probably take a good while before I get back to it, lol.

**Comment by randomdude999** [comment]
So 1.80 finally updates the C# wrapper to work with 1.60+ dlls. i'm still not sure if there's a good way to fix this issue.

at this point, there are really only 2 options as to what we can do: either bump the version or not. bumping has the advantage that old apps now correctly reject incompatible DLLs, but on the other hand, more recent apps will reject DLLs that actually work just fine. also we've had around 3 years now where 1.50 apps would wrongly try to load 1.60 dlls and i don't think i've ever heard anyone complain about that.

so i think overall it's still better to just leave the API version as is and bump it once we break API the next time, and i propose we close this issue without changing anything

**Comment by RPGHacker** [comment]
> but on the other hand, more recent apps will reject DLLs that actually work just fine

Doesn't sound like a major deal to me, honestly. If someone updates an app to use new Asar headers, they're also going to use a new DLL along with it. I also don't see much of a reason why someone else (who just uses said app) would want to downgrade the DLL. Is that a thing people actually commonly do?

That being said, I don't actually have a strong opinion on this and don't mind either solution, so I'm also fine with just keeping the API version.

**Comment by randomdude999** [comment]
the problem arises when someone wants use new asar features in an older app by replacing asar.dll with a newer version. if we bumped the api version right now, all apps built against 1.60-1.71 would reject the 1.80 dll, even though the api didn't change. this is only a minor inconvenience for open-source apps where you can just upgrade the headers and recompile, but it's almost impossible to fix any closed-source apps without having the devs update them (though i'm not too sure how many closed-source apps there even are which depend on asar)

**Comment by RPGHacker** [comment]
That's a good point and a good reason for why we should probably keep the API version, even though at most few tools should be affected by this.
