### ISSUE TITLE
Feature Request: Align PC to x bytes

### ISSUE THREAD

**Issue by KungFuFurby** [RPGHacker/asar#138]
I am looking for a new command to allow the program counter to auto-align itself to the nearest x bytes.

This would be most useful with the sample directory in SPC700 code in my case, because sample directories must be aligned to 256 bytes (and thus, the pointer for a sample directory must be aligned to 256 bytes, for example, $3300 or $2500).

**Comment by RPGHacker** [comment]
Sounds like it could be useful. Maybe we could have a variation of the pad command. Thinking of something like:
```
padbyte $00
pad align 256
```

**Comment by KungFuFurby** [comment]
Technically it could also work with...
```
fill align 256
skip align 256
```
All three normally offset the program counter by a fixed amount of bytes, and thus can be adapted to instead run until the program counter is aligned with the byte count shown. In my case, I would use skip align 256. Note that it is possible to end up shifting the program counter by zero bytes because it is already aligned.

**Comment by Alcaro** [comment]
You may want to support aligning to a multiple of N, minus K, so you can stick in a four-byte header after the align command and have the body of the data 256-aligned. Could be useful for RATS tags, for example.

...okay, you're not supposed to stamp out RATS tags manually, and I'm not sure if there are other situations where it'd be useful.

Also make sure to explicitly reject (or define behavior for) non-power-of-two alignment, or Asar will choose something for you - probably something dependent on freespace ID, not just the address.

**Comment by randomdude999** [comment]
well, `skip -5` exists and should work, so i think that one will be good enough in the tiny amount of use cases where you need it. And yeah, probably best to only have power of 2 alignment.

**Comment by Alcaro** [comment]
negative skip is disgusting

won't work either. org $0080FD : nop : align 256 : skip -4 : db "derp" : db "main data" will shred the nop

**Comment by randomdude999** [comment]
how about `<fill|skip> align <x> [offset <y>]` where offset can be negative? so e.g. `skip align 256 offset -8` for page-aligned rats tags

**Comment by RPGHacker** [comment]
I have no strong opinion on this, so I'm fine with that solution.
