### ISSUE TITLE
This patch broke on asar 1.71

### ISSUE THREAD

**Issue by GhbSmwc** [RPGHacker/asar#139]
I got a report that another user is having the same issue majorflare had with moderating [this patch](https://www.smwcentral.net/?p=section&a=details&id=19297). This is kinda strange, since I'm currently using Asar version 1.60. I wonder if the macros handling was different, or certain functions and other things also impacted.

**Comment by randomdude999** [comment]
Pretty sure the culprit is using an old version of RPG Hacker's shared library, which depended on some bit-shifting shenanigans (i.e. undefined behavior). better to update that first and try again.

**Comment by GhbSmwc** [comment]
Where can I find the updated RPG Hacker's shared library?

**Comment by randomdude999** [comment]
On his github, probably

**Comment by RPGHacker** [comment]
The lib is [over here](https://github.com/RPGHacker/SMW-Workspace/tree/master/patches/shared) (in case you're still searching). And yeah, mea culpa. Supporting those functions directly in Asar was one of the main reasons I originally started working on version 1.40.

**Comment by GhbSmwc** [comment]
Problem fixed. Thanks.
