### ISSUE TITLE
Small question: What number format does Asar uses?

### ISSUE THREAD

**Issue by GhbSmwc** [RPGHacker/asar#141]
Does asar use any of these types of number format for defines and labels?:

-integer
-floating point (single-, double- precision?)

Also, would've been nice if asar's built-in fuction includes rounding (floor, ceil) without the need of shared.asm.

**Comment by RPGHacker** [comment]
If I remember correctly, Asar uses double under the hood for most math an casts to uint32_t where needed. Not sure if this is accurate, but something along those lines. If you want to user floating point math properly, you will have to use `math round off` in your patch.

As for rounding: a rounding function should be included in the current Asar version. Check the manual for reference.

**Comment by GhbSmwc** [comment]
Looking at the documents on this repository, it appears that the floor and ceil is never mentioned.

**Comment by randomdude999** [comment]
floor/ceil are now implemented, and your question got answered, so closing this.
