### ISSUE TITLE
Allow labels in assert

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#144]
Would make assert slightly more useful (for making sure tables are as big as expected, for making sure routines end at the correct address), and is doable without creating uncomputable patches. For this, the error throwing needs to be moved to pass 2, when the precise locations of all labels are figured out.

**Comment by Alcaro** [comment]
I once lamehacked that with a `your_table_has_wrong_size: fillbyte your_table_has_wrong_size+1/cos(end-start-144)` (cos(0) is 1, anything else is rounded to 0 and throws a div by zero error). I think it's in the zsnes warning patch.

That's a pretty good argument for allowing this thing.
