### ISSUE TITLE
True or False

### ISSUE THREAD

**Issue by XBloonyX** [RPGHacker/asar#146]
I suggest adding the functions of true or false to not have to use 1 or 0 since it is very annoying to have to add a lot of code just for not adding that as a real function

I only suggest that they add it

Pliz

**Comment by p4plus2** [comment]
Asar already supports this if you use
```
True = 1
False = 0
```

Basically, you can assign a static value to a label, then they act like constants.  I vote to close this issue personally.

**Comment by RPGHacker** [comment]
I'm not sure if static labels can currenlty be used inside comparisons (did we add that feature?), but anways, an alternative idea would be to use `!true = 1` and `!false = 0` which should work everywhere.

Personally wouldn't mind implementing something into Asar directly, though it would probably be tricky to have it amount to anything more than just built-in defines, anyways, so it might not be worth the effort right now.

**Comment by p4plus2** [comment]
I realized after Alcaro corrected me that the labels in comparison is a local hack I have.  Though we still had a consensus that it probably isn't all that useful of a feature.
