### ISSUE TITLE
Can't concatenate two or more strings with commas

### ISSUE THREAD

**Issue by TheLX5** [RPGHacker/asar#153]
The following code _should_ be treated as a single line judging from the documentation [here](https://rpghacker.github.io/asar/manual/#multiline )
```
db $00,
$00,$00,$00,
$00,$00
```
It throws me the following errors:

> Errors occurred while assembling.
> error: (E5027): Invalid number. [db $00,$00,$00,$00,]
> error: (E5117): Unknown command. [$00,$00]

It can be replicated with the following codes as well:
```
db $00,
$00,
$00,
$00
```
If it has more than two values, the concatenation fails:
```
db $00,$00,
$00
```

**Comment by RPGHacker** [comment]
Oh. I bet there's a loop missing in the code. It probably only checks for a comma once per line (instead of repeatedly, as long as the line ends in a comma).
