### ISSUE TITLE
Generated Checksum is Incorrect for 3MB ROMs

### ISSUE THREAD

**Issue by RobertTheSable** [RPGHacker/asar#154]
I was working on a  patch for Fire Emblem: Monshou no Nazo(revision 1.1) and noticed that after assembling, the checksum in the internal header didn't match what SNES9x expected the header to be. I thought it might be something with my patch since I was changing the SRAM size, but when I tried to assemble a patch that didn't change the ROM at all(basically just , I saw the same problem - the calculated checksum (FF33) didn't match the original checksum(A3C2, which is what SNES9x calculated as well) even though no actual ROM data was different.

I didn't check every ROM out there, but I noticed that 4MB ROMs don't seem to be affected - I padded the Monshou no Nazo rom to 4MB with zeros and got a correct checksum. The amount of padding needed seemed to vary depending on if the ROM was headered - with an unheadered ROM I only needed a single byte of extra padding, but with a headered ROM I needed 512 bytes of padding for a correct value. Padding the ROM changed the expected checksum from SNES9x, but not the internal checksum.

A few other ROMs I checked:
Fire Emblem: Thracia 776(4MB, LoROM, unheadered) - correct checksum.
Der Langrisser with Byuu's translation patch(3 MB, LoROM, headered) - incorrect checksum.
Megaman 7 US(2 MB, HiROM, unheadered) - correct checksum.
Kaizo Mario World (2 MB, LoROM, headered) - correct checksum.

Asar version: 1.71
OS: Kubuntu 19.04
I tested on both a Linux binary I compiled and on the Windows executable run via WINE, and didn't see any difference.

If there's any more info I can provide, please let me know.

**Comment by randomdude999** [comment]
This is a "known issue" (but nobody cared enough about it to fix it) with non-power-of-2-size ROMs.
https://github.com/RPGHacker/asar/blob/021371be2146ef900f3b5492c1150fef3cb4578a/src/asar/libsmw.cpp#L452
The full checksum computing algorithm in snes9x is really complicated for some reason, I think we would be fine with something that handled 3MB, 6MB and 2.5MB but nothing more complicated than that. I'll work on this once I find a bit of time, I already know how to implement it though.

**Comment by RobertTheSable** [comment]
If the idea is to mimic what SNES9x does, I may be able to save you some time/effort as I already borrowed the logic for the "non-power-of-2-size" case for a personal build.

**Comment by Alcaro** [comment]
As far as I know, the strategy is to take the lowest set bit in the ROM size, duplicate that amount from the end, and repeat until PoT-sized.

3MB -> duplicate 1M -> 4MB -> power of two
3.5 -> duplicate 0.5 -> 4
2.5 -> duplicate 0.5 -> 3 -> duplicate 1 (i.e. four total copies of the last half-meg) -> 4
2.75 -> duplicate 0.25 -> 3 -> duplicate 1 -> 4
1MB plus 1 -> duplicate the last byte a million times -> 2MB

This matches chip-select logic with unequal-sized ROM chips. For a 3MB ROM, there's one 2M chip and one 1M; if the 2M bit is set, the access goes to the 1M chip, which ignores the 1M bit of the address. It's the most obvious way to build a NPoT-sized ROM, padded with don't-care bytes to a PoT.

This can be emulated without copying anything. To read an out-of-range byte, repeatedly clear the highest bit that's set in the address and clear in ROM size minus 1, until the address is in range.

3MB ROM, address 3MB (zero-indexed) -> clear 1M -> 2MB -> in range
3.5M, address 3.5M -> clear 0.5M -> 3M -> in range
2.5M, address 3.0M -> clear 1M -> 2M -> in range
2.5M, address 3.5M -> clear 0.5M -> 3M -> clear 1M -> 2M

To calculate the checksum as fast as possible, pad the ROM area to a power of two, then split it to N-sized chunks, where N is the lowest set bit in the unpadded ROM size. Do the out-of-range-byte calculation for the first byte in each chunk, and sum the chunk as usual (addresses are linear within a chunk). For the usual PoT ROMs, this will be exactly one chunk.

Mirroring per the first algorithm would be easier than implementing the bitmagic algorithm (you have a 16MB buffer whose end is unused for <16M ROMs, anyways), and hardcoding the common sizes is even easier. I have no strong opinion on that topic, I just felt like doing some math.

I'm not 100% sure if all math is correct, or even if that's the correct algorithm to begin with, but I think it is.

**Comment by randomdude999** [comment]
I've implemented an algorithm that should work for all roms whose size is a sum of 2 powers of 2 - that includes 2.5MB, 3MB and 6MB, so it's good enough for me. Closing this for now.
