### ISSUE TITLE
Invalid 'warnings enable' prints the error thrice

### ISSUE THREAD

**Issue by Alcaro** [RPGHacker/asar#160]
[00:42:32]  \<Alcaro> !rb as
warnings enable 1337

lda #$1234
lda #$42|$42
[00:42:32]  \<randombot999> Errors occurred while assembling.
error: (E5162): Invalid warning ID passed to warnings enable. Expected format is WXXXX where 1001 <= XXXX <= 1025. [warnings enable 1337]
error: (E5162): Invalid warning ID passed to warnings enable. Expected format is WXXXX where 1001 <= XXXX <= 1025. [warnings enable 1337]
error: (E5162): Invalid warning ID passed to warnings enable. Expected format is WXXXX where 1001 <= XXXX <= 1025. [warnings enable 1337]
[00:42:45]  \<Alcaro> uh rand can I consider that a bug?

**Comment by randomdude999** [comment]
should be in assembleblock somewhere. someone probably thought "this thing won't actually be called from inside a pass, let's just force it to throw"

**Comment by randomdude999** [comment]
https://github.com/RPGHacker/asar/blob/021371be2146ef900f3b5492c1150fef3cb4578a/src/asar/assembleblock.cpp#L1076
https://github.com/RPGHacker/asar/blob/021371be2146ef900f3b5492c1150fef3cb4578a/src/asar/assembleblock.cpp#L1089
