### ISSUE TITLE
Help with retry patch

### ISSUE THREAD

**Issue by bacon67hhs** [RPGHacker/asar#162]
Everytime I go to patch my ROM I get this error message: 

retry.asm:29: error: (E5039): SNES address 00FFD5 in read1() out of bounds. [if read1($00FFD5) == $23]
retry.asm:40: error: (E5039): SNES address 05DAA3 in read1() out of bounds. [if read1($05DAA3) == $5C]
Errors were detected while assembling the patch. Assembling aborted. Your ROM has not been modified.

Any help to fix this? All help is appreciated.

**Comment by randomdude999** [comment]
99% sure this isn't a bug with asar, go ask in smwc's/sneslab's discord instead. if it is indeed a bug then i'll reopen this
