### ISSUE TITLE
Windows Defender sees version 1.71 as a virus

### ISSUE THREAD

**Issue by robindegen** [RPGHacker/asar#164]
I'd like to point out that windows 10's Defender straight up deletes the executable because it detects it as Win32/Fuery.B!cl. I imagine this is very likely a false positive, but maybe something can be done to the build to avoid this? 

Both the zip from here as the one on smwcentral show the same problem.

**Comment by randomdude999** [comment]
there's literally nothing i can do about this. the default build is made with unsuspicious flags, and the code itself isn't particularly weird either (it's bad, but doesn't do crazy shit like modifying itself). and i definitely don't have the resources to get the executable signed. so best you can do is dig in the settings to either disable defender or whitelist asar and if possible report the false positive

**Comment by robindegen** [comment]
@randomdude999 I ended up building it myself with Visual Studio 2019 and that seems to be just fine. What compiler/version do you use for the releases?

**Comment by Kuumba123** [comment]
Yeah dude its freaken windows fault not asars , It even happens on files that you create on your on PC . not download

**Comment by robindegen** [comment]
@randomdude999 Perhaps it's related to Spectre mitigation. VS2019 is warning quite a lot about "warning C5045: Compiler will insert Spectre mitigation for memory load if /Qspectre switch specified".

**Comment by randomdude999** [comment]
we can't do anything about antivirus being dumb, closing this.
