### ISSUE TITLE
No proper error information displayed when mistyping a macrolabel within a macro

### ISSUE THREAD

**Issue by mellonpizza** [RPGHacker/asar#175]
Attached asm file provides an example code that showcases the bug, in short a typo of macrosublabel `lda .?label` where lda has an addressing width specified (.w, .l), or any other similar opcode will trigger an error but not provide any detailed information.
[macrolabelbug.txt](https://github.com/RPGHacker/asar/files/5230009/macrolabelbug.txt)

**Comment by randomdude999** [comment]
not actually related to macros, a patch containing just `db .` does the same thing. As does `db .asdf` with no parent label, or `db ?0`. I honestly can't believe nobody's noticed this before.

**Comment by p4plus2** [comment]
Found the problem, the error is reported on the wrong pass, I need to make sure the fix doesn't lead to other bugs before pushing though.

**Comment by p4plus2** [comment]
Fix has been merged,
