### ISSUE TITLE
[FEATURE REQUEST] Default values for parameters in macros

### ISSUE THREAD

**Issue by Atari2** [RPGHacker/asar#177]
It would be extremely helpful to be able to have default values for macro parameters. An example code would be like
```
macro testMacro(a = 0, b = "a")
 db <a>
 !c = <b>
endmacro
```
I leave syntax decision to the asar devs, but that would be my preferred option.
With that you'd be able to call the above macro example with 0, 1 or 2 parameters, and the non provided ones will use the specified default value.

**Comment by p4plus2** [comment]
Should default args parse math?  If so, are labels allowed?  I vote no to both personally.  Simple substitution is probably most logical.  But then that leads to some really weird parsing possible where you can have garbage default arguments.  Should those be allowed and cause errors only on instances where args are not provided?  Also, are partial defaults allowed?  That is to say `macro test(a, b = 0)`.  Should this be RTL or LTR (I vote RTL as in the example I gave).  What do we do with defines?  expand them? paste them then expand them?

**Comment by Atari2** [comment]
> Should default args parse math? If so, are labels allowed?
no to both imo, it doesn't make sense, simple numbers/strings will work for defaults.
> Also, are partial defaults allowed? That is to say macro test(a, b = 0)
yes, I think they should
> What do we do with defines? expand them? paste them then expand them?
Allowing defines to be used as default arguments sounds weird, but in the case they get used, I'd paste and then expand.

**Comment by randomdude999** [comment]
+1 to atari's comments, except i'd prefer to not ban defines

**Comment by RPGHacker** [comment]
An alternative to this could also be to enable macro overloading. Example:

```
macro my_macro(a, b)
    db a,b
endmacro

macro my_macro(a)
    %my_macro(a, 2)
endmacro

macro my_macro()
    %my_macro(1, 2)
endmacro

%my_macro()
```

Drawback: It would be a little more code to write for end users.
Benefits: It would (probably) be easier to implement into Asar, and it would support pretty much everything for default arguments (labels, defines, functions etc.).

**Comment by p4plus2** [comment]
With the new variadic macros by using `if sizeof(...) == 3` one can effectively overload and support default arguments.  Do we still want both features or do we see the one as sufficient?

**Comment by RPGHacker** [comment]
As far as I'm concerned, that's more than enough. If it can be avoided, I prefer to not have multiple solutions for the same thing, as that makes maintenance more difficult, and the variadic arguments should be just simple enough to use to not be annoying.

**Comment by Atari2** [comment]
Honestly using variadic to replace defaults feels like a cheap workaround that requires more code.
I would still like to see a "proper" default value feature added to macros.

**Comment by RPGHacker** [comment]
IMO, with Asar's code base being what it is, "cheap workarounds" will have to suffice for a lot of things. Plus, it's not really that much more code compared to supporting them properly. How often is the average coder going to use macros with default arguments, anyways?

**Comment by Atari2** [comment]
I can think of a lot of use cases where default args are really useful, maybe I'm not the average coder but eh

**Comment by p4plus2** [comment]
Make a use case where they come up often enough to justify a more specific feature over a generalized variant and I'll look into implementing them and reopen the issue.   I personally went with the variadic approach because it felt more flexible and I've had more instances desiring the latter than the former.  But, with a good motivation I'm not strictly against the idea.

**Comment by RPGHacker** [comment]
AFAIK, even Lua implements default arguments as just variadic arguments, and that's a very widely used script language. It's not a completely unheard of approach.
IMO, it's always a matter of balancing the the effort it takes to implement something VS the benefit it actually brings, and in this case, I'd say the required effort would be at least respectable, whereas the benefit it would bring would be realtively slow (since variadic macros already offer a decent workaround).

**Comment by Atari2** [comment]
I do not have the time to write down a sizeable example of how I'd use the feature but I had in scope a project where defaults would've made my life a lot easier.

If both of you are against adding this feature as of now, just close this and we'll re-discuss it when I have time to sit down a write a proper big use case good enough to warrant implementation.

**Comment by p4plus2** [comment]
I'm still open to seeing a sizable example.  I'll leave this issue open until 1.8 releases, if you can't provide motivation by that point I will close the issue.

**Comment by Atari2** [comment]
I don't have the time to provide a sizeable example, and won't have for some time, mostly due to me trying to juggle 100 things at once, so you might as well close this. If needed, I'll fall back to the variadic macros and work with those.

**Comment by p4plus2** [comment]
At this time I think I will close this issue as variadic functions act as a solution.  If a very strong case for these comes up in the future we can reopen this issue and reconsider at that time.
