### ISSUE TITLE
Add a resource file to the Asar DLL

### ISSUE THREAD

**Issue by RPGHacker** [RPGHacker/asar#18]
Add a resource file to the Asar DLL so that version information can be read directly from the DLL via Windows Explorer instead of only being accisble via the API.

**Comment by randomdude999** [comment]
It seems that there is only one version field. Should we put the Asar version there (such as 1.50) or the API version? The API version would be more useful if you wanted asardll.c to automatically extract info from the DLL, but the Asar version I feel would be more useful for the user or something.

not edit: nvm, there's 2 version fields, "file version" and "product version". I vote file version is API version and product version is Asar version.

**Comment by RPGHacker** [comment]
I completely forgot there even are two different version numbers. Let me think about this...
I'm not entirely sure how the API version is meant to be used exactly. I guess it's to assure that the DLL that an application gets is compatible with the application and not randomly an older Asar version, though to be honest, I'm not sure if we absolutely need a separate API version for this. I think it should be fine to just ues Asar's regular version number for this.

Technically, the only use of a separate API version is so that applications that were built with newer Asar versions can safely downgrade their Asar DLL as long as the API version is the same. This wouldn't work anymore if we used the actual version as the API version. However, I'm not sure if this is actually something too useful to have in the first place. I guess there are situations where you would want to downgrade to an older Asar DLL, but I think they're few. Upgrading to a newer Asar DLL is more common and more important, but that would work fine with just Asar's regular version number
(For example: an application built against Asar 1.50 should be able to safely use Asar DLL 1.60 instead).
In any case, I think the way it's currently handled isn't ideal. In fact, I think had planned to look into this some more and maybe change the Asar DLL binding a bit, anyways.

As for which version number to use then: for now, I would recommend just going with Asar's main version number for both fields. I'm not sure if there's much use in having the API version expoded in the resource file. I don't quite remember much about the resource format. How flexible is it? Would something like "v1.50, API v300" be possible in a resource file? If so, that's what I'd use. If not, I'd just use Asar's main version for now until we have thought some more about what to do with the API version in the future.
For now, my main intention in having a resource file really is convenience only, since right now you can only see the DLL's version number by loading it. Once we add a resource file, you can see its version number as a tooltip in Windows Explorer.

As for a version number for the executable, yeah, that would also be useful, compltely forgot about that.

**Comment by randomdude999** [comment]
The resource file has 2 different version fields per version type - one 
that's represented in 4 shorts (whose string representation would be 
like 1.0.0.0) and one that's text-based. I guess we could fit both the 
api version and the normal one in the 4 shorts, but then windows would 
think it's 1.50.3.0 (for asar 1.50 and api 300).

Also, I think the version number being exclusively in the version info 
would make some of the wrappers more difficult to write - for example, I 
can't find a way to get the version info from a DLL in Python without 
using external libraries.

**Comment by RPGHacker** [comment]
For the number-based one I would just go with 1.50.0.0 then (since we don't won't to confuse people into thinking it would be a newer version than 1.50 or something like that). For the test-based field we could then mention the API version (would go with something like "v1.50 (API v300)".

Yeah, we don't need to have the version number exclusively in the resource file (after all, the application needs its own version number, anways, so it doesn't hurt having a function for that). I wasn't really suggesting removing the version number function (as in asar_version()) from the API or anything, only the asar_apiversion() function if anything (and even there one could argue that removing it entirely probably isn't a great idea, since it would probably break some compatibility, but we could raise the API version number only once, rewrite the bindings to read the main Asar version from now on and then only ever change the main Asar version in future releases).

Anyways, I'm digressing here and this is basically all future talk. For now, if that doesn't break your binding, I would just stick the main Asar verison in the resource file and only put the API version in there if it can go into the text version field somehow.
