### ISSUE TITLE
Declaring Namespaces or Structs without declare a Freecode, org, freespace ,etc before.

### ISSUE THREAD

**Issue by weierstrass1** [RPGHacker/asar#181]
Hey i have the following issue, i declare this:

```
namespace nested on
base $7F0B44
namespace IAMANameSpace
  label1:
  namespace IAMAnotherNameSpace
    label2:
  namespace off
namespace off
```
If i dont declare a org or freecode before, it doesn't work properly because for some reason all Addresses change. If i do the following:

```
pushpc : freecode
namespace nested on
base $7F0B44
namespace IAMANameSpace
  label1:
  namespace IAMAnotherNameSpace
    label2:
  namespace off
namespace off
pullpc
```

It works but sends a leak warning that doesn't exist because i am patching nothing. This also happends with structs.

mod edit: fixed formatting, please use triple backticks for code blocks

**Comment by randomdude999** [comment]
can you please at least try to minify test cases instead of giving me 200 lines of code which uses undefined defines

**Comment by weierstrass1** [comment]
> can you please at least try to minify test cases instead of giving me 200 lines of code which uses undefined defines

sorry, i fixed it.

**Comment by Alcaro** [comment]
you fixed it too well, it no longer reproduces any issues. first one assembles to a blank rom without warnings, and second one correctly returns a leak warning

**Comment by randomdude999** [comment]
~~now it's not giving any warnings because you deleted all of the labels~~
i see what you're referring to, there technically isn't any org so the first label sets org and base to $8000. one fix is to use `org $7F0B44` instead of `base` - which will do pretty much exactly what you want here, as trying to write any opcodes there will still be an error.

**Comment by weierstrass1** [comment]
> ~now it's not giving any warnings because you deleted all of the labels~

LMAO, i'll add a label.

> i see what you're referring to, there technically isn't any org so the first label sets org and base to $8000. one fix is to use `org $7F0B44` instead of `base` - which will do pretty much exactly what you want here, as trying to write any opcodes there will still be an error.

oh  okay, i'll try with that.
