### ISSUE TITLE
[feature request] print tab character for console window that I can copy.

### ISSUE THREAD

**Issue by GhbSmwc** [RPGHacker/asar#184]
I was thinking the print statement to be able to include tab character on the console window. Here is an example:
```
print "$012345	-$012346"
```
When copied from the console window, the tab character is then converted into spaces, which I don't want.

This would be really helpful if there is a way I can copy the tab character from the console window. Considering that I recently made an address tracking tool: https://github.com/GhbSmwc/SMW_Addressmapper that utilizes the tab character during array processing, would be very useful for hackers to simply use that to check for potential RAM conflicts.

**Comment by RPGHacker** [comment]
I'm almost certain that Asar doesn't do any tab to space conversion itself. Pretty sure it's the console window itself that does that, so I don't think we can influence that much.

**Comment by randomdude999** [comment]
fyi asar does do tab->space, but not in quoted strings. here it's still cmd's fault

**Comment by GhbSmwc** [comment]
Looks like ``%TAB%`` doesn't work.

**Comment by TheLX5** [comment]
%TAB% is referencing a variable named TAB, of course it won't work if it hasn't been set before.

Also tabs totally work with asar, but cmd prints the tabs as 8 space characters, so as randomdude said, it's cmd's fault.

**Comment by GhbSmwc** [comment]
I'll try to add a workaround to the addressing tool, like accept both the tab character and the vertical bar character.

**Comment by RPGHacker** [comment]
Going ahead and closing this, since it's not a problem with Asar itself.

**Comment by GhbSmwc** [comment]
(if this gets opened when commenting here, I'm sorry)

So, in summary, I could do this:
```
print hex(!Freeram), "_TAB_", "1"
```

And the user can replace ``_TAB_`` after copying text from the console window and pasting it into a text editor.
