### ISSUE TITLE
feature request: output a txt file on the print command

### ISSUE THREAD

**Issue by GhbSmwc** [RPGHacker/asar#185]
I was thinking of instead of outputting the print text on the console window, to also have the ability to output as a new txt file. Maybe that could be useful not just to bypass the tab character limitation on the command prompt, but also in some cases like collaboration hacks.

**Comment by p4plus2** [comment]
Whats wrong with `asar.exe mypatch.asm myrom.sfc > output.log`?

**Comment by GhbSmwc** [comment]
Cool, solved:
```
print "$012345	-$012346"
```
Command prompt:
```
[path to asar.exe] [path to patch] [game file] > Output.txt
```
