### ISSUE TITLE
Certain SuperFX Opcodes are Ignored if Comma is Missing

### ISSUE THREAD

**Issue by Yoshifanatic1** [RPGHacker/asar#188]
If you write out SuperFX instructions that use a comma as part of their syntax like "IBT R0, #$00" but you leave out the comma by accident, when you assemble the patch, asar will silently fail to assemble these instructions. No warning, no error message, nada. Asar basically acts like the opcode isn't even in the patch at all. This isn't the case with SPC700 opcodes, as asar will give unknown command errors if you forget the comma.

You can easily test this out with the arch-superfx.asm test file by deleting all the opcodes that do not use a comma and replacing all commas in the file with a space. Then observe how the file you apply the test file to isn't changed at all.

**Comment by randomdude999** [comment]
looks like this was caused by the same bug that caused #189, which has now been fixed
