### ISSUE TITLE
readfile()'s/canreadfile()'s optional parameter is bugged

### ISSUE THREAD

**Issue by RPGHacker** [RPGHacker/asar#19]
Currently, readfile()/canreadfile() functions throw an error when providing the optional parameter and trying to open a file that doesn't exist. That shouldn't be the case; the optional parameter should only be returned in those cases.

**Comment by randomdude999** [comment]
but canreadfile() doesn't even have an optional parameter? For that, do you mean that it doesn't return 0 when the file couldn't be opened?

**Comment by RPGHacker** [comment]
Whoops, sorry. Yeah, that's what I meant. IMO, canreadfile() should not throw an error when a file doesn't exist, but just return 0 (maybe with a "file not found" warning, but not an error).

**Comment by randomdude999** [comment]
I don't think it should throw a warning. After all, it's supposed to tell you if you can read a certain file, so it should return 0 when that file doesn't exist.

**Comment by RPGHacker** [comment]
That's true, though currently there's no way to know whether canreadfile() returned 0 because of trying to read out-of-bounds or because of the file not existing at all. The canread() function doesn't have this problem since it only reads from the input file, which has to exist, so people who have used canread() before are probably only used to the function checking for out-of-bounds cases, so I think returning a warning on "file doesn't exist" woudln't be a bad idea here so that a missing file doesn't accidentally slip through because the patch writer thought they were only checking for out-of-bounds.

Of course there are also alternative solutions to this problem. Whether the function throws warnings or not could be configurable via a compiler flag. I suppose we could also add a fileexists() function, in which case it wouldn't matter too much anymore.
