### ISSUE TITLE
Forcing Absolute Addressing 

### ISSUE THREAD

**Issue by Kuumba123** [RPGHacker/asar#190]
Could we add a option to force absolute address by simply putting .a example 
STA.A Variable Name . I can't imagine it would take to much work to code since there is already one for long addressing

**Comment by KungFuFurby** [comment]
I think there is already one, but not as .a... instead, it's .w, for word addressing, referring to a two byte address.

**Comment by Kuumba123** [comment]
interesting just tested it out and it worked just fine . I thought you could only use the .w for immediate addressing

**Comment by p4plus2** [comment]
.b .w and .l all correspond to 8, 16, and 24 bit operand overrides respectively.  Of course, if you try applying an invalid size to an opcode it'll produce an error.

Fun fact: asar also will parse .d as 32 bit.  It will always produce an error though as there are no 32 bit opcodes.

**Comment by Kuumba123** [comment]
interesting

**Comment by RPGHacker** [comment]
FYI, the relevant section from the manual is [here](https://rpghacker.github.io/asar/manual/#opcode-length).

I guess we could we could update the manual to make the meaning of .b, .w and .l a bit clearer, since it currently only mentions that they specify the length of the opcode, but not what length exactly they correspond to.

**Comment by p4plus2** [comment]
An interesting idea (that I am NOT volunteering to implement....I've got enough planned atm): a "strict" command that requires .[bwl] on any ambiguous opcode.  For example h4voc (a DKC2 hacker) recently ran into an issue where `lda #0000` and `lda  #$0000` assembled differently (one got 8 bit the other 16).  Some food for thought for sure.

**Comment by RPGHacker** [comment]
Have thought about that as well, so definitely approve of the general idea.

**Comment by randomdude999** [comment]
don't we already have an opt-in warning for that?

**Comment by randomdude999** [comment]
we do, W1013 "implicitly sized immediate". looks like it's not thrown for non-immediate addressing, but there, it's generally less of a problem anyways

**Comment by randomdude999** [comment]
this issue wasn't really an issue in the first place, so i'm closing this for now
