### ISSUE TITLE
Add a filesize() and a fileexists() function

### ISSUE THREAD

**Issue by RPGHacker** [RPGHacker/asar#20]
Add a filesize() function which lets us query the size of a file (to use in conjunction with readfile() functions).

**Comment by randomdude999** [comment]
should I add this to my pull request? It doesn't seem too difficult.

**Comment by RPGHacker** [comment]
Feel free to do so, I would certainly appreciate it. Yeah, I also don't expect it to be too difficult.

**Comment by RPGHacker** [comment]
Updated to also mention a fileexists() function, which should return 1 if a file exists, otherwise 0. Probably also wise to have this.

**Comment by randomdude999** [comment]
I assume that fileexists() should just return whether the file is readable, not whether it exists (but, for example, is owned by another user or something)?

**Comment by RPGHacker** [comment]
Personally, I think it should return whether the file exists only, because if it returns 0 for other I/O errors as well (such as "file is read protected" or whatever), that will likely confuse end users (the function would return 0 despite the queried file existing, leaving people wondering what they did wrong). Other I/O errors should be reported only when actually trying to access the respective file (which, I assume, is probably the case already, since I think functions like readfile() etc. would throw errors in that case).

**Comment by randomdude999** [comment]
That actually makes implementing it slightly more difficult to implement since I can't just open the file and see if it opened properly. Also, what are the uses for a file that you know exists but can't see? Maybe it should show a different error (or return a different value) based on whether the file doesn't exist or isn't accessible.

**Comment by RPGHacker** [comment]
Different return values seems like the best solution then. In that case, I would rename the function from fileexists() to getfilestatus() or something like that, where the file could return 0 for "file exists and no problems were found" and other values for other each other reported error.
Might also be a good idea to secretly keep the file open when calling this function on a file, kinda like what readfile() functions do. That way, we hopefully shouldn't get into the situation where a file's status changes between calling fileexists() and readfile().
