### ISSUE TITLE
Feature Request: Hirom bank cross

### ISSUE THREAD

**Issue by spannerisms** [RPGHacker/asar#205]
Managing ROM data in hirom banks that contain both code and data gets a bit verbose and tedious with all the warnpc. A new parameter to `check bankcross`, something like `check bankcross half`, that prevents code or data from crossing over `XX:7FFF` to `XX:8000` in addition to the normal `XX:FFFF` to `YY:0000` warning would be nice.

**Comment by p4plus2** [comment]
Hm.  Providing special rules for hirom could be advantageous.  To clarify: is it fair to say the desired behavior is for `half` mode to simply act on 32KB chunks?  That would seem most logical to me, I may have some use for that myself too since my homebrew is hirom.

**Comment by spannerisms** [comment]
Correct, that’s what I’m after. It would still do the normal check in addition to the half-bank check.

**Comment by RPGHacker** [comment]
Would you say that this splitting of code and data into the two halfs of a bank is a common paradigm when working with HiROM? It does sound like quite the special case, but if it's indeed a common thing, then I'd say it's a reasonable feature request.

An alternative could be being able to pass an increment to bankcross, like `check bankcross $8000`, but then I don't know if anything besides the half/half split are very common cases, either, so maybe just supporting the half border cross will be enough after all.

**Comment by p4plus2** [comment]
In HiROM you have effectively a layout that looks like this:
`40:0000-40:FFFF` is a 64KB block
`C0:0000-C0:FFFF` this is a fastrom mirror of the above
`00:8000-00:FFFF` is a mirror of `40:8000-40:FFFF`
`80:8000-80:FFFF` is a fastrom mirror of `00:8000-00:FFFF` aka `C0:8000-C0:FFFF`
Yes, you are reading that correct, there can be between two and four ways to reference a single address.


It is common practice to use and then use 32KB `0000-7FFF` blocks for small data and the place code in the `8000-FFFF` portion (so you have access to WRAM and MMIO mirrors.  Typically a 64KB block is use for "large data" (Think level data or music) as it can cross banks much easier as it is contiguous.

To be honest, "half" mode has no major impact on LoROM (maybe with banks 40+ you would have issues...).  I'd almost be inclined to suggest it should simply be the default.

**Comment by p4plus2** [comment]
Implemented and committed.  Needs a minor bugfix for windows (min apparently has scope bleeding on gcc but not msvc.  So I need to poke that into the windows build)

Additional testing needs done, feel free to play around with it for now though.

**Comment by p4plus2** [comment]
Fixed MSVC bug and added a test.  Going to close this issue now.
