### ISSUE TITLE
Division by label sometimes gives moving labels

### ISSUE THREAD

**Issue by Alcaro** [RPGHacker/asar#210]
[12:35:55]  <Alcaro> !rb as
org $008000
dl 1/(x-$008003)
x:
[12:35:55]  <randombot999> Errors occurred while assembling.
<input>:3: error: (E5048): Division by zero. [dl 1/(x-$008003)]
<input>:4: error: (E5066): Internal error: A label is moving around. Please create an issue on the official GitHub repository and attach a patch which reproduces the error. [x:]

Any simpler constellation gives the first error only, and it doesn't seem possible to trigger this 5066 without a div by zero (or at least some other operation that only gives errors on some passes - are there any?). I'm not sure if it's worth fixing, but we should at least know about it.

**Comment by p4plus2** [comment]
Fixed, albeit with a bandaid.
