### ISSUE TITLE
Add a command to verify the title of the output ROM

### ISSUE THREAD

**Issue by RPGHacker** [RPGHacker/asar#22]
Add a command to verify the title of the output ROM and throw an error if it doesn't match. for example:
`expect "SUPER MARIOWORLD     "`
This allows us to make sure that a certain patch is only used with a certain ROM.

Apparently a function like this has existed in Asar at some point, but was removed for an unknown reason.

**Comment by randomdude999** [comment]
Would `expecttitle` be a better name for it? IMO it's a bit clearer.

**Comment by randomdude999** [comment]
Also what should this do with the --no-title-check option? Should that make title errors simply be ignored, or should the patch-defined title errors still apply? I vote to disable the patch-defined ones when the option is specified.

**Comment by RPGHacker** [comment]
expecttitle sounds fine to me.
As for --no-title-check, not sure. If I remember correctly, the title check is only supposed to check the title for garbage data, not whether it has a certain name. That being said, someone who uses this option and thus doesn't care about the ROM containing a garbage title probably also doesn't care about the ROM containing a "wrong" title, so I guess ignoring the command with the option disabled might be a good idea. I can think of at least one use case where that would be useful. Maybe you're working on an SMW hack and want the ROM to have a proper title instead of "SUPER MARIOWORLD", so you're changing the title, but now none of the patches work anymore because of expecttitle, you you use --no-title-check to make them still work. That sounds like a potential (albeit rare) use case.

Alternative idea: downgrade the error to a warning when --no-title-check is used. That might be the safe solution here.
