### ISSUE TITLE
Padding and RATS tag problem in 1.71

### ISSUE THREAD

**Issue by DiskPoppy** [RPGHacker/asar#235]
I know it's from an older version, but it isn't in the changelog. The issue is unneccessary padding and wrongly sized RATS tags around the bank border.
[bugtest.zip](https://github.com/RPGHacker/asar/files/8207648/bugtest.zip)

**Comment by randomdude999** [comment]
https://github.com/RPGHacker/asar/commit/8a5c808356c96fbe4647ef4d3c2883f6aa4329f3

most likely was fixed by this. we have a terrible track record of maintaining the changelog properly
