### ISSUE TITLE
Asar 1.81 has an issue saying: warning: (W1029): A mapper has already been selected. [sa1rom]

### ISSUE THREAD

**Issue by ferminacostajr** [RPGHacker/asar#244]
I had issues of that thing, even though I patched SA-1 patch, and I tried to patch the nuke_statusbar.asm into my ROM, it says A mapper has already been selected. sa1rom

**Comment by p4plus2** [comment]
This is only a warning.  If your patch works you can disable the warning if you would like.

That being said, this warning appears when two different mappers are selected in the same instance of asar.  This can happen for example if you incsrc a patch that uses `lorom` when your base patch uses `sa1rom`  (or some other similar permutation)

The proper solution is to make sure all patches you apply use the correct mapper consistently.  If you believe the warning is triggered incorrectly, please provide a test case and we will investigate further.

**Comment by ferminacostajr** [comment]
I removed the lorom one and it patched great

**Comment by p4plus2** [comment]
Excellent.  I will close this issue then.

**Comment by ferminacostajr** [comment]
And I believe for lorom is add to !bank = $8000
