### ISSUE TITLE
(bug) newlines break nested macros

### ISSUE THREAD

**Issue by blackmagemathos** [RPGHacker/asar#246]
encountered this bug while trying to use a shared subroutine inside another in pixi (props to @Atari2 for identifying the exact issue)

👇 this compiles
```
macro include()
    incsrc "a.asm"
endmacro

macro macro_without_newline()
endmacro

org $008000
%include()
;@file a.asm
lda ?test_label
%macro_without_newline()
?test_label:
```

👇 this doesn't
```
macro include()
    incsrc "a.asm"
endmacro

macro macro_with_newline()

endmacro

org $008000
%include()
;@file a.asm
lda ?test_label
%macro_with_newline()
?test_label:
```
and produces the following error :
`a.asm:1 (called from <input>:11): error: (E5060): Label ':macro_0_test_label' wasn't found. [lda ?test_label]`

**Comment by randomdude999** [comment]
i wanna do a better fix for this later too though. currently using incsrc in a macro still creates a somewhat broken state, which should work most of the time but you can still run into more weird bugs

**Comment by blackmagemathos** [comment]
oh, i had no idea this had already been reported privately- apologies and thanks for your work then :)

**Comment by randomdude999** [comment]
okay, i think i properly fixed this now - incsrc should behave much more consistently with regard to macros now. and well, the original bug was already fixed yesterday, so closing this for now
