### ISSUE TITLE
petition to ban if+endwhile

### ISSUE THREAD

**Issue by Alcaro** [RPGHacker/asar#269]
\<Sir Walrus> !rb as2
if 1
endwhile
\<randombot999> (no output)
\<Sir Walrus> !rb as3
if 1
endwhile
\<randombot999> (no output)

ಠ_ಠ

**Comment by randomdude999** [comment]
\<trillian> !rb as2 if 1
endwhile
\<randombot999> Errors occurred while assembling.
\<input>: error: (Eunclosed_if): Unclosed if statement.
\<input>:3: error: (Emisplaced_endif): Misplaced endif.
    in block: [endwhile]

close enough i guess
