### ISSUE TITLE
MVP and MVN documentation

### ISSUE THREAD

**Issue by jeffythedragonslayer** [RPGHacker/asar#283]
The syntax for MVP and MVN should be in the asar documentation for people coming from other assemblers.

**Comment by Alcaro** [comment]
It's MVN $dst,$src. MVN $srcdst works too.

I agree that "documentation" is awful. It contains at least one mistake, too - BRL takes $0000, not $00.

**Comment by RPGHacker** [comment]
Added a note on order of parameters to the manual in 2b29a7d. Not sure if there's anything else that should be done about this.
Also fixed the BRL thing. So I think the issue can be closed.
