### ISSUE TITLE
[Asar2] Phantom Error when using array indices

### ISSUE THREAD

**Issue by hellow554** [RPGHacker/asar#285]
This code produces the following error:

```asm
org $8000

dw BgmArray[0]

BgmArray:
    dw 0
```

`: error: (Ephantom_error): A phantom error occurred. This is an Asar bug, please report it: https://github.com/RPGHacker/asar/issues`

If you replace `BgmArray[0]` with `BgmArray+0`, it works, but I like the array syntax more, because `BgmArray` is a struct in my case, not a simple label.

**Comment by randomdude999** [comment]
phantom error fixed, and this syntax now works with all structs. (doesn't work with regular labels though, asar has no clue what their size should be.)
