### ISSUE TITLE
Add UTF-8 support to " and ' delimited strings/characters

### ISSUE THREAD

**Issue by RPGHacker** [RPGHacker/asar#31]
Very low priority (and probably a bit messy), but it would be kinda nice to add UTF-8 support to tables, print commands and table files in a future version of Asar.

I remember working on some German patchs in the past where umlauts like ÄÖÜ caused problems and I had to write these characters as hex values instead. My VWF patch would certainly greatly benefit from this feature, but I think it would be useful to international users in general. Code compatibility should still be granted, since code uses only ASCII commands. Some strings using ANSI characters >= 128 might break from a transition, but there should only be few cases like that and they wouldn't break too horribly - only some characters would get replaced by garbage characters or disappear.

**Comment by ExE-Boss** [comment]
This would be useful for my [Core Dump patch](https://github.com/ExE-Boss/SMW-Workspace/tree/master/src/core_dump), which uses UTF-8 to store text in the ROM.

https://github.com/ExE-Boss/SMW-Workspace/blob/master/src/core_dump/core_dump.asm#L404-L513

**Comment by p4plus2** [comment]
This has been completed in the asar2 branch.  It will not be backported.  Closing.
