### ISSUE TITLE
check title command

### ISSUE THREAD

**Issue by hansbonini** [RPGHacker/asar#320]
`check title` didn't find a match for title when rom file is `Megaman X3 [U] [!].smc`. Tried with different mapping modes.

It occurs on 1.91 build.

**Comment by RPGHacker** [comment]
How exactly did you use `check title`? Did you pass in the name of the ROM? If so, that would be incorrect. You're supposed to pass in the name in the ROM's header (which is usually displayed whenever you open a ROM in an emulator). If I remember correctly, whitespace also needs to be included.

**Comment by hansbonini** [comment]
`check title "MEGAMAN X3            "`

![image](https://github.com/RPGHacker/asar/assets/3918305/165b4d81-7057-4d3f-8f31-3ccf8c4066a9)

command line output:
```
$ asar.exe main.asm 'Mega Man X 3 (U) [!].smc'       
Error: The ROM title appears to be "á▒á@♥®▼øTø♀Ô0½¯íøkk┬ ", which looks like garbage. If this is the ROM title, add --no-title-check to the command line options. If the ROM title is something else, use snespurify on your ROM.
```

Addresses are mapped incorrect too, `lorom` was used.
These issues only ocurrs with this game. I'm able to use all features with other games.

**Comment by RPGHacker** [comment]
Okay, so I guess is either it's some weirdness with headers, or with mapping modes. 🤔
What's the size of the ROM in bytes?
Does it happen with all Mega Man X3 ROMs, or only with this particular (presumeably headered) one?

**Comment by hansbonini** [comment]
![image](https://github.com/RPGHacker/asar/assets/3918305/16abbebc-09e4-46b1-84cb-3ee5157080be)
No header is present on this rom.


![image](https://github.com/RPGHacker/asar/assets/3918305/46bc427c-ba34-4cff-bab4-d72343970178)
It works on japanese version.

![image](https://github.com/RPGHacker/asar/assets/3918305/bb3d07b0-12d9-4fc5-878f-7156dcfee5f8)
It works on european version.

Edit:
![image](https://github.com/RPGHacker/asar/assets/3918305/34505ebc-889f-48c4-85fa-7e6a4571ebfb)
I got a rom from another source and it works. I don't have any idea what is happening, maybe a bad dump.

**Comment by RPGHacker** [comment]
Alright. I'll assume it was indeed just a bad dump, so I'll go ahead and close the issue for now. We can reopen it if the problem ever shows again on any ROM that seems to be clean.
