### ISSUE TITLE
Have a proper README.md

### ISSUE THREAD

**Issue by RPGHacker** [RPGHacker/asar#33]
Current file is just a leftover of old manual.txt. Have a proper Readme that doubles as a both a, proper overview for the GitHub page and a readme to bundle with future releases of Asar.

Things that should go into the Readme:
* Very basic, simple instructions for patch users how don't need to care about programming stuff ("double click Asar and it'll ask you for file names")
* Reference to the manual (ideally both the local and the online version) for patch programmers
* Shortly mention the Asar DLL and that its documentation can mostly be found in the headers of the bindings
* Reference to the changelog (ideally both the local and online version)

That's about it I think.

**Comment by randomdude999** [comment]
I might write this. Also, IMO we should have separate readme.md and readme.txt (although both should still be kept up-to-date) since "normal users" probably don't even know you can open .md files with notepad.

**Comment by RPGHacker** [comment]
I think there's also the possibility of replacing the .md with a .txt entirely (I **think** GitHub should also work with a txt file, but I'm not sure). Although I admit that there are some benefits to having two separate readmes: we would use markdown only for GitHub and not have it in the end user Readme. On the other hand, keeping both files in sync sounds kinda annoying, so not sure which is better. My original idea was to use a single file, but use minimal markdown so that reading the file without GitHub would not get too confusing.

**Comment by randomdude999** [comment]
GitHub works with a .txt just fine. IMO another advantage of the multiple readmes is that the GitHub one could have more developer-specific stuff (such as the way the folder structure is laid out and build instructions) which would be unnecessary for the end user (whose zip doesn't even include that stuff).

**Comment by RPGHacker** [comment]
That is a good point. Two separate files sounds like the better idea then.
In that case, I would definitely prioritize the end user TXT file, since it's actually important for a future release, whereas updating the GitHub-specific file isn't too urgent.
