### ISSUE TITLE
convert label value to hex

### ISSUE THREAD

**Issue by gizaha** [RPGHacker/asar#331]
contents of file data.bin
$a000
$c000

My asar code on another file:
!pointer #= readfile2("data.bin",0)    ;define !pointer has now value 40960, thus $a000 in decimal
!{data_!pointer} #= 0

I want to create defines taken their names from data in data.bin file, i mean
!data_a000, !data_c000 etc. 
However !pointer returns decimal value, so it creates defines !data_40960 instead of !data_a000.
Is there a solution to that?
Adding a $ before readfile2 didn't work.

**Comment by RPGHacker** [comment]
I think there is no solution in current Asar that wouldn't involve a huge, nasty heap of hellish, hard-to-maintain macro sorcery. I think Asar currently simply doesn't feature any builtin functionality for converting numbers to formatted strings, except inside print statements.

Can you tell us more about your specific use case? Maybe we can propose a workaround solution that won't require this functionality. What is the .bin file and why do the defines need to match the hex values inside? How do you intend to use them?

**Comment by gizaha** [comment]
I already use workaround.
I will try to explain it simple:
Snes rom have many "files" within the rom, compressed gfx data.
I decompress them and include them to msu file for faster load.
Filenames are original snes addresses, let's say cf4af3.pic

While decompiling the rom with Diztinguish, the original gfx loader read pointers of files 
I hijacked the code, to try to read from msu instead of rom*

pointer table:
db $02                        ;2 means compressed
dl GFX_CF4AF3   

it would be nice to do this small change
db $03                       ;3 means msu
dl !GFX_CF4AF3


so !GFX_CF4AF3 = msu_address
I use workaround but there are 30 of this files, it would be nice to be easy and simple.

* Of course i add additional code in order to read from msu and dma to vram.

**Comment by gizaha** [comment]
Change my mind. Please delete this issue.
