### ISSUE TITLE
Add new asar_patch_ex() API function to the other bindings

### ISSUE THREAD

**Issue by RPGHacker** [RPGHacker/asar#34]
Recently added an asar_patch_ex() function to the DLL C API, but forgot to add it to the other APIs (like C#). There are tools out there which use the C# binding in particular, so it's something that should be added before the next release.

**Comment by randomdude999** [comment]
I added it to the python wrapper (although I'm not too sure the include path thing is correct), but I don't know enough C# to update that wrapper.

**Comment by RPGHacker** [comment]
I can probably do the C# wrapper myself, I think. Just haven't really gotten to do anything Asar-related those past few days.

**Comment by randomdude999** [comment]
For the python wrapper it would be more convenient to just always use asar_patch_ex instead of asar_patch. Would that be okay?

**Comment by RPGHacker** [comment]
Yep, that should be no problem. Since nothing uses the Python wrapper yet, there isn't really any compatibility that can break.

**Comment by randomdude999** [comment]
Closed by #80.
