### ISSUE TITLE
Bug with includes and subfolders

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#38]
Basically, readfile (line 532 @ main.cpp) gets thisfilename==<the filename we're including> so it tries to use thisfilename as the base for the path we're including which is bad. Solution (maybe): set thisfilename after calling readfile.

**Comment by randomdude999** [comment]
(the effect of this means that incsrc/incbin with subfolders almost never finds what you want it to find)

**Comment by RPGHacker** [comment]
Huh, that's weird. Do you have an example of some concrete paths, we might get here, maybe along with a test which reproduces the error? I'm assuming this happens with files which include files which include files?
Doesn't the code eventually do dir() on thisfilename before revoling paths? In other words, it should always end up with the actual directory of the current file and thus correctly build the path to the new file?

Or is this just a missunderstanding in general? Relative include paths should always be relative to the file currently being assembled. Is that not the case right?

**Comment by randomdude999** [comment]
Here's an example folder structure:
```
main
| patch.asm
\ SPC
  | bank_1D.asm
  \ SFX
    | sfx.asm
    \ sfx_01.bin
```
patch.asm includes SPC/bank_1D.asm.
bank_1D.asm includes SFX/sfx.asm.
sfx.asm includes sfx_01.bin.
patch.asm can find bank_1D.asm, bank_1D can find sfx.asm, but sfx.asm can't find sfx_01.bin.

**Comment by RPGHacker** [comment]
Alright, thanks for the details. And I assume sfx.asm just contains
`incbin sfx_01.bin`
is that correct?

**Comment by randomdude999** [comment]
Yes, that's correct. I think it's because thisfilename will get set to whatever the path to the included file is, but that's not necessarily the actual path to it (not relative neither absolute), but it will be relative to the previous thisfilename.

**Comment by randomdude999** [comment]
Really the issue is that the absolute path of the current file is never stored. It could be used for the relative path detection instead of the path that the file was included as, which might be relative to the wrong thing. As in, when bank_1D.asm is being assembled, thisfilename = "SPC/bank_1D.asm" which is quite fine until we start assembling SFX/sfx.asm in which case thisfilename = "SFX/sfx.asm" which is not relative to the root path or anything.

**Comment by RPGHacker** [comment]
I see what you mean. thisfilename only stores whichever path was used to include a file (I somehow thought it was always an absolute path), and when a relative path gets in there, the application tries to open further includes with a relative path, which it will likely interpret as relative to the current working directory (and thus fail). If so, I have a couple of ideas on how to fix this. Will take a look later.
