### ISSUE TITLE
Improve cmake configuration

### ISSUE THREAD

**Issue by RPGHacker** [RPGHacker/asar#48]
Some of the stuff in our current cmake configuration is considered bad, outdated practice nowadays (for example: writing CMAKE_CXX_FLAGS directly). I've found a nice and comprehensive [blog post](https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/) on recommendations for modern cmake. Should be a good idea to take a look at it and improve our configuration at some point.

**Comment by randomdude999** [comment]
Would you say the current cmake config for the tests is good? Because if yes then I could easily make similar modifications to the main cmake file.

**Comment by RPGHacker** [comment]
Yeah, that seems better. I think it's mostly the CMAKE_CXX_FLAGS stuff that we should replace by target_compile_options()/target_compile_features() etc.
