### ISSUE TITLE
Support pass-through of string parameters in user-defined functions

### ISSUE THREAD

**Issue by RPGHacker** [RPGHacker/asar#56]
Basically, something like this should be possible:

```
function readfilenormalized(filename, pos)=readfile1(filename, pos)/255
```

Right now, it will throw an error because it thinks all parameters in user-defined functions are doubles. I think one simple way of fixing it could be to allow optional specification of data types in user-defined functions:

```
; pos defaults to ": double" here because nothing is specified.
function readfilenormalized(filename : string, pos)=readfile1(filename, pos)/255
```

**Comment by randomdude999** [comment]
I'm pretty sure we could use asar's string-double compound parameter type for this.

**Comment by RPGHacker** [comment]
That's the idea. However, it needs to know what parameters a function takes when it is defined, otherwise it'll throw an error when using the function, because right now, it always sets the expected parameter to "double" for user-defined functions, so it will throw an error when it actually gets a string instead.

Another idea would be to not set parameters to "double" by default and instead set them to a new "undefined" type that only gets resolved when a function is actually called (so kinda Ruby-/Python-styled) Not sure how well this would work out, though, could be somewhat hacky.
