### ISSUE TITLE
SA-1 mapping broken for some addresses

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#61]
TheBiob on discord (in a DM with me):
> also, telinc reminded me of another bug I forgot yesterday, If I'm correct somethings broken with the pctosnes routine for sa-1 roms
> If I'm correct then my debugging a while ago showed that the 0x0F8000 can cause it to mask out the high nibble of the bank byte causing it to overwrite a completely different bank to what it's supposed to be

("the 0x0F8000" probably references libsmw.h line 157)

Not sure if this is still relevant and even if it is then how to fix it, but I think it's worth a look.

**Comment by RPGHacker** [comment]
Not really too familiar with certain SNES stuff (and especially the SA-1) myself, so someone else would have to take a look at this one.

**Comment by randomdude999** [comment]
When I asked telinc1 on discord:
> all I know is that it breaks GPS
> I've considered looking into it, maybe I should
> I recently got quite good with memory maps (:wink:), so I could probably see what causes it

**Comment by randomdude999** [comment]
pctosnes seems to be incorrect for every address in the $10:0000-$1F:FFFF range. For $10:0000 it returns $00:8000.

**Comment by RPGHacker** [comment]
What is it supposed to map to?

**Comment by randomdude999** [comment]
All that I know about this is that pctosnes($100000) returns $008000, and this is incorrect for every pc address until $1FFFFF, but when I tried to fix that, stuff broke even more.

**Comment by TheLX5** [comment]
I don't know if this is going to help, but sa1rom makes the freespace finder go crazy.

Using the following testcase:
```
sa1rom

org $008000

macro insert()
freedata
print pc
	incbin 32kib.bin
endmacro

%insert()
%insert()
%insert()
%insert()
%insert()
%insert()
%insert()
%insert()
%insert()
%insert()
```
Returns:
```
118000
138000
158000
178000
198000
1B8000
1D8000
1F8000
018000
038000
058000
078000
```
With a bunch of errors messages in between, but still manages to happen on my recently patched SMW ROM with SA-1 and returns the same issues using a similar macro:

```
macro insert_gfx(filename,add)
    org ($00A304+!base3+($<add>*3))
        if read2($00D067|!base3) == $DEAD
            autoclean dl <filename>_gfx
        else
            dl <filename>_gfx
        endif
    warnpc $00A38B|!base3
freedata
    print pc
    <filename>_gfx:
        incbin powerups_files/graphics/<filename>.bin
endmacro
```

```
asar powerup.asm power_sa1.smc
198000
1B8000
1D8000
018000
038000
058000
```

**Comment by TheLX5** [comment]
Yeah, I get that @ first paragraph and meant the stuff regarding the addresses.

Also, Vitor told me that sa1rom is working fine on asar 1.37 (it's the version he uses for his hack), so I went ahead and did another test with my patch, and can confirm that it's working fine in asar 1.37.
Results of the same macro on my patch, but using [asar 1.37](https://www.smwcentral.net/?p=section&a=details&id=13386&r=0):
```
asar powerup power_sa1
198000
1B8000
1D8000
218000
238000
258000
278000
298000
2B8000
2D8000
2F8000
```

I guess it would be good to see what was changed between 1.37 and 1.50 that made sa1rom to be broken.

**Comment by RPGHacker** [comment]
Weird. I don't even think I changed anything about SA-1 mapping, but I might be wrong. Maybe something else broke it. I will take a look.

**Comment by RPGHacker** [comment]
I'm assuming the bug exists in both 1.40 and 1.50, right?

**Comment by TheLX5** [comment]
I have no access to v1.40, so I can't test it.

**Comment by RPGHacker** [comment]
Ah, true. SMWC never moderated v1.40 and it was eventually updated to v1.50, so it doesn't exist in the version history.

If you can make me a simple patch which reproduces the problem, I can take a look later at home.

**Comment by TheLX5** [comment]
[sa1rom_test.zip](https://github.com/RPGHacker/asar/files/1902703/sa1rom_test.zip)
Contains an asm file and a 32KiB bin file. The asm file is supposed to be patched after patching [SA-1 Pack 1.26](https://www.smwcentral.net/?p=section&a=details&id=15116) to a clean SMW ROM, but if you just create a sfc file out of the asm file, asar still will throw similar, if not the same, numbers as the ones I posted above, except it will whine about a few (irrelevant) things.

**Comment by randomdude999** [comment]
All right, I'll dig out 1.37's SA-1 mapping code.
nvm, i''m using 1.35 because i have that in my downloads for some reason
## Asar 1.35
### snestopc
```c
if ((addr&0x408000)==0x008000)
{
	return sa1banks[(addr&0xE00000)>>21]|((addr&0x1F0000)>>1)|(addr&0x007FFF);
}
if ((addr&0xC00000)==0xC00000)
{
	return sa1banks[(addr&0x700000)>>20]|(addr&0x1FFFFF);
}
return -1;
```
### pctosnes
```c
for (int i=0;i<8;i++)
{
	if (sa1banks[i]==(addr&0x600000)) return 0x008000|(i<<21)|((addr&0x0F8000)<<1)|(addr&0x7FFF);
}
return -1;
```
### getpcfreespace
```c
rebootsa1rom:
int nextbank=-1;
for (int i=0;i<8;i++)
{
	if (i&2) continue;
	if (sa1banks[i]+0x100000>romlen)
	{
		if (sa1banks[i]<=romlen && sa1banks[i]+0x100000>romlen) nextbank=sa1banks[i];
		continue;
	}
	int pos=trypcfreespace(sa1banks[i]?sa1banks[i]:0x80000, sa1banks[i]+0x100000, size, 0x7FFF, align?0x7FFF:0);
	if (pos>=0) return pos;
}
if (autoexpand && nextbank>=0)
{
	unsigned char x7FD7[]={0, 0x0A, 0x0B, 0x0C, 0x0C, 0x0D, 0x0D, 0x0D, 0x0D};
	romlen=nextbank+0x100000;
	romdata[0x7FD7]=x7FD7[romlen>>20];
	autoexpand=false;
	goto rebootsa1rom;
}
```
These seem to be the only places where sa1rom is used.

## Master branch
### snestopc
```c
if (mapper==sa1rom)
{
	if ((addr&0x408000)==0x008000)
	{
		return sa1banks[(addr&0xE00000)>>21]|((addr&0x1F0000)>>1)|(addr&0x007FFF);
	}
	if ((addr&0xC00000)==0xC00000)
	{
		return sa1banks[((addr&0x100000)>>20)|((addr&0x200000)>>19)]|(addr&0x0FFFFF);
	}
	return -1;
}
if (mapper==bigsa1rom)
{
	if ((addr&0xC00000)==0xC00000)//hirom
	{
		return (addr&0x3FFFFF)|0x400000;
	}
	if ((addr&0xC00000)==0x000000 || (addr&0xC00000)==0x800000)//lorom
	{
		if ((addr&0x008000)==0x000000) return -1;
		return (addr&0x800000)>>2 | (addr&0x3F0000)>>1 | (addr&0x7FFF);
	}
	return -1;
}
```
### pctosnes
```c
if (mapper==sa1rom)
{
	for (int i=0;i<8;i++)
	{
		if (sa1banks[i]==(addr&0x600000)){ return 0x008000|(i<<21)|((addr&((i<4) ? 0x0F8000 : 0x1F8000))<<1)|(addr&0x7FFF);}
	}
	return -1;
}
if (mapper==bigsa1rom)
{
	if (addr>=0x800000) return -1;
	if ((addr&0x400000)==0x400000)
	{
		return addr|0xC00000;
	}
	if ((addr&0x600000)==0x000000)
	{
		return ((addr<<1)&0x3F0000)|0x8000|(addr&0x7FFF);
	}
	if ((addr&0x600000)==0x200000)
	{
		return 0x800000|((addr<<1)&0x3F0000)|0x8000|(addr&0x7FFF);
	}
	return -1;
}
```
### getpcfreespace
```c
rebootsa1rom:
int nextbank=-1;
for (int i=0;i<8;i++)
{
	if (i&2) continue;
	if (sa1banks[i]+0x100000>romlen)
	{
		if (sa1banks[i]<=romlen && sa1banks[i]+0x100000>romlen) nextbank=sa1banks[i];
		continue;
	}
	int pos=trypcfreespace(sa1banks[i]?sa1banks[i]:0x80000, sa1banks[i]+0x100000, size, 0x7FFF, align?0x7FFF:0, freespacebyte);
	if (pos>=0) return pos;
}
if (autoexpand && nextbank>=0)
{
	unsigned char x7FD7[]={0, 0x0A, 0x0B, 0x0C, 0x0C, 0x0D, 0x0D, 0x0D, 0x0D};
	romlen=nextbank+0x100000;
	writeromdata_byte(0x7FD7, x7FD7[romlen>>20]);
	autoexpand=false;
	goto rebootsa1rom;
}
```
freespace isn't supported in bigsa1rom.

**Comment by randomdude999** [comment]
Diff:
```diff
9c9
<     return sa1banks[(addr&0x700000)>>20]|(addr&0x1FFFFF);
---
>     return sa1banks[((addr&0x100000)>>20)|((addr&0x200000)>>19)]|(addr&0x0FFFFF);
17c17
<     if (sa1banks[i]==(addr&0x600000)) return 0x008000|(i<<21)|((addr&0x0F8000)<<1)|(addr&0x7FFF);
---
>     if (sa1banks[i]==(addr&0x600000)){ return 0x008000|(i<<21)|((addr&((i<4) ? 0x0F8000 : 0x1F8000))<<1)|(addr&0x7FFF);}
33c33
<     int pos=trypcfreespace(sa1banks[i]?sa1banks[i]:0x80000, sa1banks[i]+0x100000, size, 0x7FFF, align?0x7FFF:0);
---
>     int pos=trypcfreespace(sa1banks[i]?sa1banks[i]:0x80000, sa1banks[i]+0x100000, size, 0x7FFF, align?0x7FFF:0, freespacebyte);
40c40
<     romdata[0x7FD7]=x7FD7[romlen>>20];
---
>     writeromdata_byte(0x7FD7, x7FD7[romlen>>20]);
```
files i diffed:
[1.35.txt](https://github.com/RPGHacker/asar/files/1903967/1.37.txt)
[master.txt](https://github.com/RPGHacker/asar/files/1903968/master.txt)

**Comment by RPGHacker** [comment]
At least some of those changes were definitely made prior to 1.40. Quote from v1.37 changelog:

> * New freespace argument added; a $xx byte that will search the ROM for contiguous sections of that byte. Before it was hardcoded to only search for $00. Default is still $00 if not supplied, so past patches should not be broken.
> ...
> * Fixed SA-1 mapping using wrong Super MMC banks range.

The final line is the only that I know is from me (>= v1.40), but I doubt it's related to address conversion in any way. Everything else is either stuff I did but forgot about, or stuff that I merged at some point.

**Comment by randomdude999** [comment]
New diff:
```diff
20c20
<         romdata[0x7FD7]=x7FD7[romlen>>20];
---
>         writeromdata_byte(0x7FD7, x7FD7[romlen>>20]);
61c61
<             if (sa1banks[i]==(addr&0x700000)){ return 0x008000|(i<<21)|((addr&0x0F8000)<<1)|(addr&0x7FFF);}
---
>             if (sa1banks[i]==(addr&0x600000)){ return 0x008000|(i<<21)|((addr&((i<4) ? 0x0F8000 : 0x1F8000))<<1)|(addr&0x7FFF);}
```
[master.txt](https://github.com/RPGHacker/asar/files/1904132/master.txt)
[1.37.txt](https://github.com/RPGHacker/asar/files/1904133/1.37.txt)

Hmm, looks like I tried to fix the right line, but in the wrong way. Can we try just using 0x0F8000 always?

**Comment by randomdude999** [comment]
All right, I reverted it to the 1.37 behavior in commit e9f83ec01f6aef8ea6d32f47a8edf4a55c437ac3. Hopefully it works now. I'll make a pull request once someone confirms it's working.

**Comment by RPGHacker** [comment]
Would still be a good idea to find out when exactly that was changed and why. After all, it's possible that this change was meant to fix some bug, in which case the bug would return after reverting it.

Have to check v1.40 and v1.50 to see if I did that (and if so, what for).

**Comment by randomdude999** [comment]
1.50 is the same as the current master (the one without the fix). The changelog for 1.40 doesn't mention SA-1 at all though, so I would assume it's similar to 1.37. Then again, 1.50's changelog doesn't mention SA-1 either, so where did the change come from?

**Comment by RPGHacker** [comment]
That's what I'm wondering, too. Since I'm the only one who worked on v1.40 and v1.50, I must have done it, but I absolutely don't remember why and what for...

Well, I also manually merged some stuff from p4plus2's modified Asar version in v1.50, mainly for struct support. I guess it might be possible that he had the change on his branch and I blindly copied it over without knowing what it was for? That's a very theoretical possibility, but I guess I can find out by checking his GitHub.

**Comment by randomdude999** [comment]
All right, feel free to add those fixes to the fix-sa1 branch too.

**Comment by RPGHacker** [comment]
I can't switch branches right now because I have some uncommited local changes (unless git has something like shelves? I'm not too familiar here).

Can you add that fix from Vitor to your branch? I will merge the branch afterwards.

**Comment by randomdude999** [comment]
Sure.
Also, [I've found 1.40](https://bin.smwcentral.net/u/28555/asar140.zip), looks like it didn't have the weird fix.
Also i think `git stash` would do what you want, but i haven't used it.

**Comment by RPGHacker** [comment]
Yeah, I've merged p4plus2's stuff in v1.50, so I figured if it was related to that, it must have happened there.

Alright, I will take a look.

**Comment by randomdude999** [comment]
LX5 said it worked fine on his powerups patch. If telinc finds something tomorrow, i'll reopen this, but for now I think it's fixed.

**Comment by randomdude999** [comment]
On discord (#asm of the SMWC server):

Telinc1: @randomdude999 doesn't look like either of the dlls solve the GPS bug
randomdude999: do your roms work with asar 1.37?
Telinc1: the 1.37 dll? let's try
Telinc1: asar 1.37 and gps 1.2.31 break, too
randomdude999: well then it's a different bug
Telinc1: gps 1.3.0 refuses the 1.37 dll
TheBiob: What exactly is it doing?
Telinc1: overwriting bank 2
Telinc1: but it's sometimes another bank
Telinc1: that's not where acts like settings go

He gave me a ROM that reproduces it though, I'll work on it.

**Comment by randomdude999** [comment]
Looks like the issue was actually the fact that Telinc had a 8 MB ROM, but tried to use the normal (up to 4 MB) SA-1 mapping. GPS tried to overwrite the start of bank C1, which is in the last 4 MB in the full SA-1 mapping, but first 4 MB of the normal mapping.
