### ISSUE TITLE
More powerful if statements

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#62]
Someone on discord mentioned that `if (!a == 3) && (!b == 4)` doesn't work.
This could be 'fixed' by making the comparison operators work like real operators (by adding them to the list of `oper` calls in math.cpp:836), and just make `if` evaluate its argument and check whether it's 0.
This would break compatibility with comparing strings though (which I'm pretty sure we don't want to do).
The way to fix that would be to make the entire math system use a string/double compound type (like the function parameter type), and just throw errors everywhere where numbers are expected and strings are given.

**Comment by RPGHacker** [comment]
Do if statements support string comparisons in the first place? I'm not quite sure.

Another workaround that is already possible is to use the built-in functions that were added in (I think) 1.40. For example, you do do something like this here:

```
if and(equal(!a, 3), equal(!b, 4))
```

**Comment by p4plus2** [comment]
Closing as this no longer appears to be a problem.
