### ISSUE TITLE
Add floor, ceil, truncate functions

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#67]
Rquested by GreenHammerBro in the Asar thread.

**Comment by RPGHacker** [comment]
He also sent me a PM, to which I replied:

> You should already be able to define those yourself with what Asar currently provides. See [here](https://github.com/RPGHacker/SMW-Workspace/blob/master/patches/shared/shared.asm).

```
	; Returns the truncated value of a decimal number
	; Note that pure unsigned int conversion acts weirdly on most negative numbers here, which is why we actually need the select()
	
	function trunc(decimal_number) = select(less(decimal_number, 0), -(abs(decimal_number)|0), decimal_number|0)
	
	
	; Returns the fractional part of a decimal number
	; This originally used (decimal_number%1) internally, but that ended up being ridiculously inaccurate in some cases
	; This version actually seems to work better in those cases, so I hope it's also the overall better solution
	
	function frac(decimal_number) = decimal_number-trunc(decimal_number)
	
	
	; Returns the floor of a decimal number
	
	function floor(decimal_number) = trunc(decimal_number)-select(less(decimal_number, trunc(decimal_number)), 1, 0)
	
	
	; Returns the ceiling of a decimal number
	
	function ceiling(decimal_number) = -floor(-decimal_number)
```

> Not sure if these implementations are reliable since I haven't used them a huge deal. Also not sure whether I'd want to add them directly to Asar since I don't want to overload Asar with functionality (makes it more difficult to maintain), so I tend to only add built-in functions that are either very basic or are impossible to do outside of Asar. I'd say these are something that should go in a shared lib instead (like the one I linked above). If they don't work reliably, I think it should be possible to make more reliable version using the round() function (probably coupled with a few select() here and there).

So yeah, as stated there, I'm a bit mixed on adding them directly to Asar, since I don't consider them essential and think they should be easy to implement as user functions with what is currently supported by Asar, so I think they should probably go into a shared library or something like that.

**Comment by randomdude999** [comment]
Yeah, that actually sounds like a much better idea. I'll just close this then. Although i think we should mention it in the thread anyways.

**Comment by RPGHacker** [comment]
Yeah, that's a good idea.
