### ISSUE TITLE
Add some short instructions on how to install syntax highlighting extensions

### ISSUE THREAD

**Issue by RPGHacker** [RPGHacker/asar#69]
Based on what GHB mentioned on SMWC, installing the syntax highlighting extension for Asar in Notepad++ doesn't seem to be self-explanatory, so short instructions on how to do that (as well as for the Sublime syntax highlighting) would probably be useful.

Not sure where the best place to put them would be. On one hand, the manual's focus is on Asar functionality itself, so it might seem intuitive to put that information into readme.txt. On the other hand, I think syntax highlighting is mostly irrelevant to average Asar users and is only useful to coders, so the manual might be a better place for that after all.

**Comment by randomdude999** [comment]
I think it should still go in readme.txt, since the manual covers patches themselves and readme.md is for tool programmers. Besides, readme.txt already has a section on writing patches.

**Comment by RPGHacker** [comment]
Sounds reasonable. If it's kept short and simple (maybe also with a note that this step is optional and/or mainly relevent to patch writers), it definitely shouldn't cause any harm in readme.txt, so that might be the best place to put it.
