### ISSUE TITLE
print double() is broken

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#70]
for `print double(x)`, x can not contain parentheses (or commas, i think). The first closing parenthesis is interpreted as the end of the double() call. I'm not sure how to fix this, other than just keeping track of the parentheses yourself. Pointed out by GreenHammerBro on SMWC (although you gave him the broken solution, RPG Hacker).

**Comment by RPGHacker** [comment]
I assume something with the math parser is behaving badly when using the double() function. Probably only when not using the optional parameter? The function is definitely supposed to parse math correctly, like dec() and hex().

**Comment by RPGHacker** [comment]
```
while (*pos != ',' && *pos != ')' && *pos != '\0') pos++;
if (*pos == '\0') error(2, "Mismatched parentheses");
```

This here in assembleblock.cpp is probably the culprit. It only parses until the first closing parenthesis, not until the last.

**Comment by randomdude999** [comment]
That's what I meant when I said "keep track of the parentheses yourself". Pseudocode:
```
int parens_level = 0;
while true:
    if (parens_level == 0 && *pos == either ',' or ')') break;
    if (*pos == '\0') error(2, "Mismatched parentheses");
    if (*pos == '(') parens_level++;
    if (*pos == ')') parens_level--;

**Comment by RPGHacker** [comment]
It's probably not even needed. We probably just have to read until the last parenthesis, create a substring and then pass it to getnumdouble(). If my assumption is correct, that function should already complain about mismatching parentheses somewhere down the line. Unless, of course, there's a comma in the string, in which case we pass everything up to the comma to getnumdouble(). I think this should be the simplest way to fix the function.

An alternate idea would be to check if the string contains a comma. If it does, take the one path. If it doesn't, do the exact same thing hex() and dec() do, except with the double function (and the default precision).

**Comment by randomdude999** [comment]
You'll also have to account for the fact that there may be 1 argument, but the string may still contain a comma: for example `double(round(100/3, 0))` has 1 argument to pass to getnum but it contains a comma.

**Comment by RPGHacker** [comment]
That's a good point. I was like "math expressions can't contain commas", but I completely forgot math expressions can contain function calls.

**Comment by randomdude999** [comment]
Actually, I think what you would want to use is the qpsplit function: it splits the input string, but it automatically handles parentheses and quotes and doesn't split inside those.

**Comment by RPGHacker** [comment]
~~But... but... I like reinventing the square wheel so much... 😢~~
No, you're right, it's one of those functions whose excistence I completely missed.
