### ISSUE TITLE
Built-in tests are broken

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#8]
Some of the tests (namely v140features.asm, v150features.asm, bigincbin.asm, tablefiles.asm) fail. This is because of the way the tests are rearranged but their includes are unchanged, leading to Asar looking for them in the wrong place.

**Comment by RPGHacker** [comment]
It's on my to-do list (should probably add issues for all my to-dos when I get to it). The plan is to introduce include search paths (probably based on the pull request by zetaPRIME) into Asar. Once used in the test, this should fix the problem.
