### ISSUE TITLE
Bug evaluating function parameters

### ISSUE THREAD

**Issue by KevinCathcart** [RPGHacker/asar#86]
While working on a pull request for a different issue I noticed that the following code fails fails the assert statement, when obviously it should succeed:
``` asm
org $8000
function test(abc,ab) = abc+ab
assert test(1,2) == 3
```
Pull request that contains a fix will be sent shortly.

**Comment by RPGHacker** [comment]
Very interesting. Maybe some kind of string compare issue? Have seen those a couple of times in regards to functions. Maybe it's actually doing `ab + ab` because `ab` is fully contained in `abc` and it doesn't compare the full string or something like that.

**Comment by RPGHacker** [comment]
Yup, I think that is the case.
```
if ((int)strlen(userfunc[i].name)==len && !strncmp(start, userfunc[i].name, (size_t)len))
[...]
```
In math.cpp, line 567.

**Comment by RPGHacker** [comment]
(Actually, not sure - len might just be the name of the current parameter)

**Comment by RPGHacker** [comment]
That line is just evaluating the function name, not the parameters, whoopsie. The bug is probably not far from there, though.
