### ISSUE TITLE
Asar 1.5 applies FastROM mapping in SA-1 mode

### ISSUE THREAD

**Issue by ExE-Boss** [RPGHacker/asar#88]
Discovered when testing the [32×32 Player Tilemap Patch 1.2](https://github.com/ExE-Boss/SMW-Workspace/tree/master/src/32x32_tilemap).

Confirmed still happening in the latest build.

**Comment by RPGHacker** [comment]
Can you explain what exactly this means? Maybe provide an example patch which reproduces the problem?

**Comment by RPGHacker** [comment]
I think Alcaro once tried to remove all the automatic FastROM mapping stuff, but didn't quite accomplish it because Asar is still somehow doing it internally.

**Comment by ExE-Boss** [comment]
Derp, [turns out it was on my side](https://github.com/ExE-Boss/SMW-Workspace/blob/de835097c106df740e38f1a3894024d1d43f009a/src/32x32_tilemap/ow_mario.asm#L211-L212).
