### ISSUE TITLE
Warn when changing the ROM mapping mode after parts of the patch were already assembled

### ISSUE THREAD

**Issue by ExE-Boss** [RPGHacker/asar#89]
This led to me opening #88, which turned out to have been caused by forgetting to remove two lines.

This is something you don’t want to do accidentally, and it’s like [one of C/C++’s many footguns](https://chuttenblog.wordpress.com/2018/02/23/perplexing-graphs-the-case-of-the-0kb-virtual-memory-allocations/).

**Comment by RPGHacker** [comment]
Seems like a reasonable idea, although I'm wondering whether maybe there might be some cases where someone want to switch to noram for a bit and then back to whatever mapping was previously acting. Not sure if such a scenario is likely, but maybe it would make sense for certain types of homebrew? Hard to say.
It's definitely something to consider, though, it does sound useful and reasonable.

**Comment by ExE-Boss** [comment]
> Seems like a reasonable idea, although I'm wondering whether maybe there might be some cases where someone want to switch to noram for a bit and then back to whatever mapping was previously acting.

That’s why I suggested a warning and not an error.

**Comment by RPGHacker** [comment]
Fair point.

**Comment by p4plus2** [comment]
Closing this issue as a warning for this issue has been added.  In rare instances where you don't want the warning asar has a built in mechanism to disable warnings which can be leveraged.
