### ISSUE TITLE
Asar doesn't generate checksum for ROM if part of it was assembled in norom

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#90]
https://github.com/RPGHacker/asar/blob/145f2efaa0a5db53ea317d2fce9a1e7ae8da8e72/src/asar/assembleblock.cpp#L2055-L2061
This disables generating the checksum, but it is never reset when changing to a different mapper, so a checksum is never output for ROMs that switch to `norom` for writing some large data (like my homebrew), but switch back to `lorom`/`hirom` later.

**Comment by RPGHacker** [comment]
I'm not quite sure how to best solve this. I think not automatically reenabling the checksum fixer can be a good idea in some cases. Even if the last mapping in some code is lorom, it still doesn't necessarily mean that the entire ROM has to be lorom and that the checksum location is known. Maybe a better idea here would be to let users enable or disable checksum fixing as needed? Either via a command line argument or via a command in Asar, not quite sure what's best.

**Comment by randomdude999** [comment]
I'd be in favor of a new command here. Ideally `checksum off` to explicitly disable checksum generation, and `checksum on` to explicitly enable checksum generation using the last mapper active in the patch. Ideally these should override the automatic mapper-based detection, so `checksum on` at the start of a file, then `norom` in the middle, and then `lorom` at the end would still generate a checksum.

**Comment by RPGHacker** [comment]
Sounds like a good idea to me.
