### ISSUE TITLE
Test suite broken on linux

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#94]
```
pi@raspberrypi:~/asar/build/tmp $ cat emptysublabel.asm.log
Errors were detected while assembling the patch. Assembling aborted. Your ROM has not been modified.
```
This breaks the error checking. All the actual errors are on `stderr`, which is not redirected.
https://github.com/RPGHacker/asar/blob/4352b6d8e91deab5cda437b981cb57b2ddd2cf2b/src/asar/interface-cli.cpp#L54-L63
This writes the errors to `stderr`.
https://github.com/RPGHacker/asar/blob/4352b6d8e91deab5cda437b981cb57b2ddd2cf2b/src/asar-tests/test.cpp#L307
The returned file handle is a handle to `stdout`, not `stderr`.
A hacky way to fix this would be to just include redirection in the comand to execute (`command 2>&1`).

I'm not sure how this even works on windows.

**Comment by RPGHacker** [comment]
According to my quick Google search, that actually seems like the proper solution here and not a hack.

https://stackoverflow.com/questions/6900577/c-popen-wont-catch-stderr

As for Windows, this here is probably the relevant part:

```
si.hStdError = write_handle;
si.hStdOutput = write_handle;
```
