### ISSUE TITLE
Spurious warning when adding a label to ram addresses in lorom mode

### ISSUE THREAD

**Issue by KevinCathcart** [RPGHacker/asar#96]
``` asm
lorom
org $7e3456
MyLabel:
skip 2
```

Gives the warning: ``It would be wise to set the 008000 bit of this address.``

It is trying to warn against using address ranges $0000-7FFF in banks $40–$6F and banks $C0-$EF, which only sometimes work in loram style mappings. (If they use the MAD-1 decoder chip those addresses are open bus.)

Warning for those ranges of addresses makes good sense. Warning for them in banks 7E and 7F very much wrong, since those are always WRAM. 

The story about warning in banks $70-7D and $F0-FF is interesting. Technically those areas are where SRAM is supposed to go. But in games that do not use SRAM the warning may be valid for these addresses too, since the simplest carts will mirror rom here. Unfortunately asar does not know if the game uses SRAM or not, and this warning on these banks would be very misleading for games that do use sram.

Therefore I suggest the that this if stamement:

https://github.com/RPGHacker/asar/blob/44899c6924a54b0dd83b4c464be46d81e613d3c3/src/asar/assembleblock.cpp#L1287

be updated to something like: 
```C++
 if ((mapper==lorom || mapper==exlorom) && (num&0x408000)==0x400000 && (num&0x700000) != 0x700000) ...
```

**Comment by randomdude999** [comment]
An `org` inside RAM isn't valid anyways, i think you want to use `base`. If the only thing that's shown is that warning then the `snestopc` routine is broken (by allowing an `org` inside the RAM area).
Also, the high pages of banks 70-7D can be used for ROM even if the game uses SRAM. (There's some conflicting information about this in different documents - for example the [SNES Programming wikibook](https://en.wikibooks.org/wiki/Super_NES_Programming/SNES_memory_map#LoROM) says that the area is ROM, but some documents say the entirety of banks 70-7D are SRAM. [Fullsnes](http://problemkaputt.de/fullsnes.htm#snescartlorommappingromdividedinto32kbanksaround1500games) says that some boards use the entire banks 70-7D as SRAM, but the only boards that do that only have ROM up to bank 1F, so those aren't the target of Asar's LoROM mapping anyways.).

**Comment by randomdude999** [comment]
Okay looks like an `org` in RAM is valid as long as you don't actually write any bytes there. I'd remove the warning for banks 7E and 7F only (for the reasons I mentioned in the previous comment). The `snestopc` routine isn't broken because apparently it's not even called until something is about to be written to the ROM. (Which makes sense, thinking about it. There's really no reason to internally use pc addresses everywhere.)
